### ISSUE TITLE
question on convergence

### ISSUE THREAD

**Issue by hmorzaria** [James-Thorson-NOAA/VAST#109]
I am testing if VAST models converge by examining the final gradient values and the Hessian. For several models, one metric indicates that the model converged and the other one that it didn't.
What is your advice for these cases? are there any tips or tricks on parameters to tinker with? 

`
 Check convergence via gradient (should be TRUE)

      convergence.test <- try(all(abs(Opt$diagnostics$final_gradient)<1e-6 ))

Check convergence via Hessian (should be TRUE)

      convergence.test2 <- try(all(eigen(Opt$SD$cov.fixed)$values>0))`

**Comment by James-Thorson** [comment]
Can you copy-paste the output of Opt$diagnostics?

The next step depends upon whether it's close to converged, or if some
parameter is hitting a bound.

**Comment by James-Thorson** [comment]
I have now added `VAST::check_fit` which is automatically used in `FishStatsUtils::fit_model` and can be used to diagnose obvious optimization issues.  

Regarding your original question:  if the Hessian is positive definite, increasing `newtonsteps` will generally result in passing the gradient-check.  However, if the Hessian is not positive definite, you probably have a parameter at a bound, as check_fit would identify
