### ISSUE TITLE
Error from Data_Fn with Version = "VAST_v5_1_0"

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#121]
Updated from Version v4_2_0 to v5_1_0, this error appears after running the TmbData=DataFn()

Error in "spde" %in% names(Return) : object 'Return' not found

I specify.
TmbData = Data_Fn("Version"=Version, "FieldConfig"=FieldConfig, OverdispersionConfig"=OverdispersionConfig,  "RhoConfig"=RhoConfig, "ObsModel"=ObsModel,  "c_i"=as.numeric(Data_Geostat[,'spp'])-1, "b_i"=Data_Geostat[,'Catch_KG'],   "a_i"=Data_Geostat[,'AreaSwept_km2'], "v_i"=as.numeric(Data_Geostat[,'Vessel'])-1,    "s_i"=Data_Geostat[,'knot_i']-1, "t_i"=Data_Geostat[,'Year'], "a_xl"=Spatial_List$a_xl,   "MeshList"=Spatial_List$MeshList, "GridList"=Spatial_List$GridList, "Method"=Spatial_List$Method,  "Options"=Options,  "CheckForErrors"=FALSE )

**Comment by James-Thorson** [comment]
Please try updating package VAST

**Comment by LuisACubillos** [comment]
I was reproducing the single-species example "EBS_pollock" (available on VAST), but the following error appears after running the TmbData=DataFn()

Error in Data_Fn(Version = Version, FieldConfig, RhoConfig = RhoConfig,  : 
  'FieldConfig' must be: 0 (turn off overdispersion); 'IID' (independent for each factor); 'AR1' (use AR1 structure); or 0<n_f<=n_c (factor structure)
In addition: Warning message:
In matrix(ObsModel_ez, ncol = 2, nrow = n_e, byrow = TRUE) :
  data length exceeds size of matrix

**Comment by kellijohnson** [comment]
@EllenY many times the error 'Return' not found will be produced when the `Version` isn't found. Make sure that you don't have .cpp in your `Version` string and that the version exists as an executable, where the following should be `TRUE`
```
Version %in% gsub("\\.cpp", "", dir(system.file("executables", package = "VAST")))
```
