### ISSUE TITLE
adding spatial exclusion zones

### ISSUE THREAD

**Issue by Craig44** [James-Thorson-NOAA/VAST#145]
Hi there,

I am curious to know if there are any functions or if anyone has had any success in adding exclusion areas in the middle of grid? for example an island, this relates to an earlier issue #92. Also related is a recent [presentation](http://www.capamresearch.org/sites/default/files/skaug.pdf) by Hans Skaug 

Cheers

**Comment by agruss2** [comment]
I think that a solution would be to implement soap film smoothers in VAST - I think that @James-Thorson recently mentioned this idea. 
For more information on soap smoothers, see:
* Wood, S.N., Bravington, M.V., Hedley, S.L. 2008. Soap film smoothing. Journal of the Royal Statistical Society, Series B 70: 931-955.
* Augustin, N.H., Trenkel, V.M., Wood, S.N. and Lorance, P. 2013. Space-time modelling of blue ling for fisheries management. Environmetrics 24: 109-119.

**Comment by Craig44** [comment]
Thanks @agruss2 . 
I was thinking that, but just checking no one had already implemented it.

**Comment by Craig44** [comment]
Thanks for the response, I was concerned with the latter of those two options, so thanks for pointing out the component I need to dig into.

**Comment by jkbest2** [comment]
Hi Craig,

Jim looped me in on this as I've been doing some related work. Probably the best reference I've seen is [Bakka et al. 2016](https://arxiv.org/abs/1608.03787). They use the SPDE method to decorrelate more quickly over barriers. This is a type of nonstationarity in the spatial field. Hans's presentation mentions that just using equation 22 from [Lindgren et al. 2011](https://doi.org/10.1111/j.1467-9868.2011.00777.x) doesn't work. This equation just says that you can do a log-regression on the covariance parameters to achieve some nonstationarity in the spatial field. I was hoping to explore this for barriers (i.e. using an indicator variable for the barrier and adjusting the decorrelation distance through that), but I haven't quite gotten there yet.

At this point, I think your best bet is probably to use the barrier functions in the `inla` package (e.g. `inla.barrier.fem` to get the relevant FEM matrices. These can then be passed to TMB as sparse matrices and be used to form the precision matrix of the spatial field. A couple caveats with this:

1. I'm not positive this will work, as I don't know exactly how the barrier method is implemented in INLA. The INLA folks have always been helpful to me on their mailing list, so it could be worth asking there if these matrices can be exported the same as for a stationary field.
2. I'm not sure the best way to pass these into VAST, but that's a better question for @James-Thorson .

**Comment by James-Thorson-NOAA** [comment]
Just a quick note that the barrier-SPDE option is now available in VAST.  It is currently undergoing testing by Cecilia O'Leary.  VAST can also exclude some areas through user-controlled specification of the extrapolation-grid, either by specifying a shapefile or a data-frame representing extrapolation-points.
