### ISSUE TITLE
Possible VAST_v5_4_0 Compatabilty issues (2)

### ISSUE THREAD

**Issue by latreesedenson** [James-Thorson-NOAA/VAST#149]
Hi,

I just updated to the newer version of VAST and tried to run the "Iceland_cod" example. I had two issues pop up:

1) The Data_Fn() function that is included with the current install of VAST_v5_4_0  does not seem to recognize the current version. I get the following error:
```{r}
Error in Data_Fn(Version = Version, FieldConfig = FieldConfig, OverdispersionConfig = OverdispersionConfig,  :   `Version` provided does not match the list of possible values
```
When I just copy, paste, and run the current `Data_Fn()` code from GitHub, things work.

2) I get the error below after I run `Build_TMB_Fn()`. After some further digging I think the issue might be with the  `param_Fn()`.
```{r}
Error in "L1_z" %in% names(Return) : object 'Return' not found
```
I tried the same work around as for the first issue and I got the same error.

Best,
LaTreese

**Comment by latreesedenson** [comment]
I believe I installed from the default, "master".

**Comment by James-Thorson** [comment]
I can't replicate your error, and just ran the cod example using the code on the master branch (I did have to make a small change in the example script for icelandic cod to check the newer, more stringent error checks regarding encounter probabilities, and pushed that small change to the development example script).

can you please instead try another species and report back with more details?

**Comment by latreesedenson** [comment]
After reinstalling VAST, and restarting R I was able to get the EBS pollock example to work.
