### ISSUE TITLE
How to calculate areas for each knot (a_xl)

### ISSUE THREAD

**Issue by ShotaNishijima** [James-Thorson-NOAA/VAST#164]
Hi Jim,

I'm wondering how to calculate areas for each knot (a_xl) by Spatial_Information_Fn.
Is a_xl associated with area for each sample (a_i)? 
Is the method different between Mesh or Grid?
Is a_xl calculated based on a triangulation in the Meth option?
I'm a little bit confused...

Shota

**Comment by James-Thorson-NOAA** [comment]
> Is a_xl associated with area for each sample (a_i)?
No, separate data objects.

> Is the method different between Mesh or Grid?
Grid is not well maintained and I don't recommend exploring it.  But yes, same method w.r.t. `a_xl`.

> Is a_xl calculated based on a triangulation in the Meth option?
Not really.  Its just calculating the set of extrapolation-grid cells closest to each knot x, and summing their area to get `a_xl` for each stratum l.

Using the new feature `fine_scale=TRUE` (currently in development branch and soon to be in release 2.2.0) eliminates `a_xl` and replaces it with `a_gl` (area of each extrapolation grid cell), and interpolates all density estimates to that finer scale.  So there's changes coming soon. Feel free to email me directly to clarify your questions.
