### ISSUE TITLE
Within year temporal effects in VAST

### ISSUE THREAD

**Issue by camposjc** [James-Thorson-NOAA/VAST#166]
Hi Jim-
We are working through a couple of datasets, including CalCOFI larval abundance data and the juvenile rockfish trawl survey data, for which within-year temporal effects (e.g., months, julian day periods/bins) are fairly important.  We have not found discussion about just how to include such effects in recent documentation but expect that it is quite feasible to do so, can you let us know (or remind us) of what the best approach for dealing with within-year temporal effects might be in developing annual relative abundance indices?  Thank you!

**Comment by James-Thorson** [comment]
Yeah, accounting for seasonal effects is an interesting topic, thanks for asking!

There's two options, one simple and a better, complicated one:

1.  Simple -- including standardized calendar date as a linear or quadratic term as catchability covariate `Q_ik`.  This assumes that expected log or logit-catch rate everywhere changes as a linear or quadratic effect of sampling date, and then "controls for" this effect (i.e., predicts density at `Q_ik=0`) when calculating derived quantities

2.  Complicated -- using VAST release >= 3.0.0, including standardized calendar date as a covariate `X_itp` and using a spatially-varying coefficient model for that term (with or without an additional linear effect or quadratic main effect), but not including the same variable in `X_gtp`.  This would estimate spatial patterns in expected catch rates for different calendar dates, while again "controlling for" this effect (i.e., predicting densities at `X_itp`=0).

I'm a little doubtful that option 2 would be feasible without some hand-holding for me, but see the User Manual and `?make_data` input `Xconfig_ztp` if you want to explore the concept further (and feel free to write me to get a draft paper on spatially-varying coefficient models).  option 2 has the benefit of allowing for spatial seasonal patterns, whereas option 1 is simple to implement, but assumes that seasonal patterns are nonspatial (following a common pattern across space)

**Comment by camposjc** [comment]
Thank you Jim, much appreciated!  We will explore option 1 in the near
term, for our short term needs, but I think it would be great to invest the
effort in exploring option 2 for some of these datasets where we actually
do have reason to think that parturition (larval output) varies in both
time and space (for the CalCOFI data) and that consequently the pelagic YOY
rockfish abundance (or possibly other YOY groundfish, such as hake) would
vary over both time and space) may as well.  I will follow up with you on
some separate threads once we've explored a bit and made some progress
about what might make sense-
cheers, John

**Comment by James-Thorson** [comment]
Sounds good!  As I said, I'd love to publish a demonstration (complete with permanently available, shareable data) demonstrating option 2, and would be happy to sink some time into such an effort
