### ISSUE TITLE
Questions about FieldConfig vs RhoConfig & catchability coeffs

### ISSUE THREAD

**Issue by klomori** [James-Thorson-NOAA/VAST#168]
Hi,

I get that the FieldConfig controls the spatial & spatio-temporal variation and that the RhoConfig controls the temporal and spatio-temporal variation, but how are you able to specify the number of factors for the temporal var (Why isn’t the temporal variation included in the FieldConfig)? And why is the epsilon (spatio-temporal variation) controlled by both the FieldConfig and RhoConfig?

My second question is regarding the catchability coefficients. Can these be both discrete and continuous?

Thanks

**Comment by James-Thorson** [comment]
`FieldConfig` can be used to specify different structures for intercepts, see e.g.:

```R
library(VAST)
settings <- make_settings( 50, "Other")
settings$FieldConfig
```

and change values in the 3rd row.

epsilon can be specified to have some structure across categories (via `FieldConfig`) and also across years (via `RhoConfig`).  Feel free to keep asking on this thread as useful
