### ISSUE TITLE
Issue with the "fit_model" function

### ISSUE THREAD

**Issue by agruss2** [James-Thorson-NOAA/VAST#172]
I am using VAST release 3.0.0, the "development" version of FishStatsUtils, and the latest version of TMB (which I just downloaded). 
I am interested in understanding why some models did not converge for one of our projects (the fish condition study), so I'm trying to use the "fit_model" function. 
Unfortunately, I'm getting the following error message when attempting to run the "fit_model" function:

> Error : 'fit_tmb' is not an exported object from 'namespace:TMBhelper'

Do you know what could be done here? 
Thanks a lot!

**Comment by ChristineStawitz-NOAA** [comment]
Hi Arnaud - I hit this recently and was able to fix it by installing the latest TMBhelper, in case it helps!

**Comment by James-Thorson-NOAA** [comment]
thanks Christine, should work!

**Comment by agruss2** [comment]
@ChristineStawitz-NOAA Thank you very much! It worked. The thing is that I wrongly assumed that installing the latest version of TMB would automatically lead to the installation of the latest version of TMBhelper. So that everything is clear to anyone running through this issue in the future, here's how to install TMBhelper:

> devtools::install_github("kaskr/TMB_contrib_R/TMBhelper")

**Comment by ChristineStawitz-NOAA** [comment]
@James-Thorson-NOAA I imagine other people are going to run into this again if @agruss2 and I did. If you give `TMBhelper` a version number for the current release and update the `VAST` DESCRIPTION file to be `Imports: TMBhelper (>=1.0.0)` you can prevent others from hitting it.

**Comment by James-Thorson-NOAA** [comment]
After testing different options, I've changed `.onAttach` in the development branch to check the semantic-version number of `TMBhelper` and update as necessary.
