### ISSUE TITLE
Option sd_site_logdensity seems incompatible with finescale 

### ISSUE THREAD

**Issue by colemonnahan** [James-Thorson-NOAA/VAST#173]
I have a really simple model using finescale=TRUE that solves in about 15 seconds but the sdreport part would run for hours if not days before I killed it. When I changed to this option:

"SD_site_logdensity"=FALSE

it ran quickly (30 seconds). So it appears that option is not compatible with finescale=TRUE. I suggest setting it off or at least warning the user.

This is with VAST release 3.0.0 and v8_0_0.

**Comment by James-Thorson-NOAA** [comment]
just added a warning in development branch of `VAST`
