### ISSUE TITLE
Confusion about dimensions in covariate arrays/matrices

### ISSUE THREAD

**Issue by embiuw** [James-Thorson-NOAA/VAST#174]
Jim,
I'm a bit confused about covariate array dimensions. In the help file for fit_model in the latest development version of VAST (3.0.0), it says: 

X_gtp	array of density covariates for each extrapolation-grid cell g, time t, and covariate p; if missing, assumed to not include covariates

X_itp	array of density covariates for each extrapolation-grid cell i, time t, and covariate p

I would have expected that "X_itp" had first dimension i=number of samples, rather than number of extrapolation grid cells (which for "X_gtp" are indexed by 'g'). 

In a previous email to me, you've suggested covariates for every sample should be included in an array called "X_ip", and I was assuming this is equivalent to "X_itp" in the latest version? Is there a typo in the help page or is it correct that "X_itp" should also e specified for each extrapolation grid cell? 

Thanks!
Martin

**Comment by James-Thorson-NOAA** [comment]
Thanks for flagging typo, docs now fixed in development branch.

And its X_itp to allow for one possibble format for multiseason models, see vignette here: https://github.com/James-Thorson-NOAA/VAST/wiki/Specifying-covariates
