### ISSUE TITLE
X_itp dimension

### ISSUE THREAD

**Issue by aastarloa** [James-Thorson-NOAA/VAST#175]
Hi there, 
My question here is related to the dimension/format of X_itp. As far as I understand, these are the covariates values associated to our samplings, where we have different number of samplings sites depending on the year (some years have more data, other have less). 

However, when we create the X_itp, it has a regular size where the number of rows are the numbers of rows in our sampling data and the columns are years. But we do not have values for all years across all sites, so how do we end up with a regular array with no NA’s?  And why are values repeated across columns if they are supposed to be years? 

**Specifying covariates example in wiki:**
X_ip = as.matrix(example$sampling_data[, dimnames(X_gtp)[[3]] ])
dim(X_ip) 
#6158    2
head(X_ip)
 BtmTemp Strat
1     7.3   0.5
2     5.6   6.5
3     5.5   3.7
4     9.8   0.5
5     5.5   3.5
6     5.2   3.7

Expand to expected size of input                                                  
X_itp = aperm( outer(X_ip, rep(1,dim(X_gtp)[2])), perm=c(1,3,2) )
dim(X_itp)
#6158    9    2

m<-X_itp[,,1] #same values across columns
head(m)
 [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
1  7.3  7.3  7.3  7.3  7.3  7.3  7.3  7.3  7.3
2  5.6  5.6  5.6  5.6  5.6  5.6  5.6  5.6  5.6
3  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5
4  9.8  9.8  9.8  9.8  9.8  9.8  9.8  9.8  9.8
5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5
6  5.2  5.2  5.2  5.2  5.2  5.2  5.2  5.2  5.2

Thanks in advance

**Comment by James-Thorson-NOAA** [comment]
For now, please just coerce it to the dimensions `X_itp` following the example here: https://github.com/James-Thorson-NOAA/VAST/wiki/Specifying-covariates.  The expanded dimensionality is used in an old format for addressing seasonal (or other ways of defining multiple temporal scales) models

I'll elaborate on my explanation and/or consider a change of input format if other people also raise this question.

**Comment by aastarloa** [comment]
Hi again, 
I came back to this point and saw the new formula interface. However, the structure of the data set I loaded differs from the one in the example and it's hard for me to follow. I don't know if I am loading an old or a new version, but I don't see any covariates_data. What I see is sampling data, Region, strata and X_xtp . So, should I assume that covariates_data is now to X_xtp?
Thanks

**Comment by James-Thorson-NOAA** [comment]
You'll need to know if you're loading the old or new version; please see `packageVersion(.)` and check against recent release numbers on github.

Then, use formula to specify which covariates to use, and `covariate_data` is a data frame with columns for `Lat` `Long` and `Year` plus other named covariates.  `make_covariates(.)` then processes these inputs to create `X_xtp` and `X_itp` to save you time in formatting.  The FishStatsUtils development branch has updated doxgen docs to explain in more detail.

**Comment by aastarloa** [comment]
Hi, 
I was certainly using the old version. I am now working with the new one and trying to add the covariates. I run the example and I have few questions:
- If we are only modelling bottom depth, what do these plots (covariates 1-predicted, covariates 2-predicted, covariates 3-predicted and covariates 4 predicted) mean?  
I made a subset of covariates_data to ensure that only bottom depth was included, and still got 4 plots.
- And, don't we need to specify the variable that we want to predict with in X_xtp? 
Many thanks

**Comment by James-Thorson-NOAA** [comment]
please play around with the formula interface, its including as many covariates as terms in the spline.  you could explore linear and quadratic etc.

I'm sorry but I don't know what's happening with your own data.  please try bridging more slowly and explain the output for the error in more detail.

**Comment by aastarloa** [comment]
Ok, thanks. The problem was solved after rescaling the covariates.
