### ISSUE TITLE
Error when using stratas

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [James-Thorson-NOAA/VAST#176]
We are trying to run VAST such that we get out strata specific biomass estimates.  Currently, I can run VAST without strata ("strata" = data.frame("STRATA" = "All_areas")) and it runs completely.  However, when I put in any other stratification I end up with Cholesky decomposition errors (NaNs) and estimates fail to be produced.  

I specify the strata this way:

strata.limits <- data.frame( 'STRATA' = c("shallow_s", "deep_s", "shallow_n", "deep_n"), 
                              'north_border' = c(49.0, 40.5), 'south_border' = c(34.5, 40.5),
                              'shallow_border' = c(55, 183), 'deep_border' = c(183, 400) )

which is being passed to FishStatUtils::Prepare_EBS_Extrapolation_Data_Fn and the make_spatial_info function in the same package.  Should I be approaching this another way?

**Comment by James-Thorson-NOAA** [comment]
The `strata.limits` you specified doesn't match the expectations of `make_extrapolation_info`, which you can see if you type `print(strata.limits)` on the object you formed:
```R
Region = "California_current"

strata.limits <- data.frame( 'STRATA' = c("shallow_s", "deep_s", "shallow_n", "deep_n"),
                              'north_border' = c(49.0, 40.5), 'south_border' = c(34.5, 40.5),
                              'shallow_border' = c(55, 183), 'deep_border' = c(183, 400) )

Extrapolation_List = make_extrapolation_info( Region=Region, strata.limits=strata.limits )
print(strata.limits)
colSums( Extrapolation_List$a_el )
```

> print(strata.limits)
     STRATA north_border south_border shallow_border deep_border
1 shallow_s         49.0         34.5             55         183
2    deep_s         40.5         40.5            183         400
3 shallow_n         49.0         34.5             55         183
4    deep_n         40.5         40.5            183         400

> colSums( Extrapolation_List$a_el )
shallow_s    deep_s shallow_n    deep_n 
 33372.18      0.00  33372.18      0.00 


where some of the strata have a total area of `0.0`, which results in these indices have a mean of zero and also causes standard error calculation of these indices to throw an error.  

Instead please use as `strata.limits`

```R
strata.limits <- data.frame( 'STRATA' = c("shallow_s", "deep_s", "shallow_n", "deep_n"),
                              'north_border' = c(40.5, 40.5, 49, 49), 'south_border' = c(34.5, 34.5, 40.5, 40.5),
                              'shallow_border' = c(55, 183, 55, 183), 'deep_border' = c(183, 400, 183, 400) )
```
which yields

> strata.limits
     STRATA north_border south_border shallow_border deep_border
1 shallow_s         40.5         34.5             55         183
2    deep_s         40.5         34.5            183         400
3 shallow_n         49.0         40.5             55         183
4    deep_n         49.0         40.5            183         400

> colSums( Extrapolation_List$a_el )
shallow_s    deep_s shallow_n    deep_n 
10444.957  3351.729 22927.228  7588.580 

And obviously please check that `print(strata.limits)` to make sure I correctly guessed what strata limits you intended to specify.
