### ISSUE TITLE
Error occurred in VAST-single-species-example 

### ISSUE THREAD

**Issue by joe20012318** [James-Thorson-NOAA/VAST#183]
Dear folks,
When I tried the VAST-single-species-example.Rmd in R console by the command one line by one, and found it goes well until the line 310
............................................................................................................
"Save = list("Opt"=Opt, "Report"=Report, "ParHat"=Obj$env$parList(Opt$par) ,  "TmbData"=TmbData)"
...............................................................................................................
The error happened as the "in par[-random] <- x : replacement has length zero". I do not know what is the reason, because I have not found par[-random] function inside the example code.

**Comment by joe20012318** [comment]
can someone give help？

**Comment by James-Thorson-NOAA** [comment]
I'll look eventually.  However, those Rmd examples are soft-deprecated, and please instead try the high-level "simplified" interface:  https://github.com/James-Thorson-NOAA/VAST/wiki/Simple-example, and feel free to re-open this issue if its still glitching.
