### ISSUE TITLE
make_data in VAST_v8_2_0 and plot_residuals

### ISSUE THREAD

**Issue by mintoc** [James-Thorson-NOAA/VAST#188]
Hi Jim, All, 

make_data in VAST_v8_2_0  doesn't return the relevant pieces for FishStatUtils::plot_residuals, e.g., objects "n_x", "s_i".

[MRE](https://github.com/James-Thorson-NOAA/VAST/blob/master/examples/VAST--single-species_example.Rmd)

VAST_v7_0_0 works.

Thanks,
Cóilín

**Comment by James-Thorson-NOAA** [comment]
Yeah, this is resolved on the development branch of FishStatsUtils and VAST, which I plan to push as a new numbered release soon.  Are you willing to try that and confirm whether it fixes it?

**Comment by mintoc** [comment]
Yes.

**Comment by mintoc** [comment]
Installing the development branch
```R
install_github("james-thorson/VAST", ref = "development")
```
returns an error 
```R
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/james-thorson/FishStatsUtils/tarball/2.3.0'
```
So I installed the development version of FishStatsUtils 
```R
install_github("james-thorson/FishStatsUtils", ref = "development")
```
A good many package updates later :coffee: I could install the development branch of VAST. 
`plot_residuals` now works with different arguments from the help pages but documented in the `?plot_residuals` helpful file.
