### ISSUE TITLE
Install issues using R version 3.6.0

### ISSUE THREAD

**Issue by James-Thorson-NOAA** [James-Thorson-NOAA/VAST#189]
As notes to myself and other interested people, it appears that many people have install issues for `VAST` using R (or MRAN) version 3.6.0.  

This appears to occur because 3.6.0 has added a new column to `getNamespaceInfo(.)` calls relative to earlier versions (see https://github.com/tidyverse/tidyverse/issues/179#issuecomment-501740451).  This has several consequences:

1. People using a mix of packages from V3.6.0 and <= 3.5.4 will have errors.  This occurs e.g. for most NOAA users, because IT appears to use the same folder for packages for different R installations.

2.  People installing `INLA` will find that version `INLA_18.07.12` used 3.5.4 namespace conventions, while `INLA_19.09.03` appears to use 3.6.0 conventions.  So even if using an older version of R, INLA installs the 3.6.0 namespace and then throws an error when loading.

I currently think that the solution is to install 3.6.0, and set up a new directory for all packages, or otherwise delete all old package versions.  This means that MRAN is not viable (because its still using 3.5.4), but hopefully they update soon.  

People can also check for package inconsistencies using code here: https://stackoverflow.com/questions/55925357/error-in-rbindinfo-getnamespaceinfoenv-s3methods-when-installing-factoex

**Comment by James-Thorson-NOAA** [comment]
After some futzing...

... it seems like people can use MRAN or base-R version <3.6.0 (i.e., MRAN 3.5.3), and pre-install INLA using:

```R
utils::install.packages( "https://inla.r-inla-download.org/R/stable/bin/windows/contrib/3.5/INLA_18.07.12.zip" )
```

or whatever version is appropriate.  The important piece is that using `3.5/INLA_19.09.03.zip` throws an error when loading it in 3.5.3.

**Comment by James-Thorson-NOAA** [comment]
For my final futzing of the day, I added an if-then statement to check for R versions >3.5.0 and <3.6.0, and for those versions I install `3.5/INLA_18.07.12.zip` while otherwise I install whatever version of `INLA` is the default.  Hopefully that fixes the issue in a more automated way.

**Comment by oceanconner** [comment]
Great, Thanks Jim!
