### ISSUE TITLE
Loading VAST under Windows 10 failed

### ISSUE THREAD

**Issue by Ned-Laman-NOAA** [James-Thorson-NOAA/VAST#190]
Running the following code

devtools::install_github("james-thorson/VAST", ref="3.0.0")
...
generated the following errors

** testing if installed package keeps a record of temporary installation path
ERROR: hard-coded installation path: please report to the package maintainer and use '--no-staged-install'
* removing 'C:/Program Files/R/R-3.6.1/library/00LOCK-VAST/00new/FishStatsUtils'
Error: package or namespace load failed for 'VAST':
 .onAttach failed in attachNamespace() for 'VAST', details:
  call: NULL
  error: Failed to install 'FishStatsUtils' from GitHub:
  (converted from warning) installation of package 'C:/Users/NED~1.LAM/AppData/Local/Temp/RtmpsPvcHq/file2354335075c2/FishStatsUtils_2.0.0.tar.gz' had non-zero exit status
Error: loading failed
Execution halted
*** arch - x64
Downloading GitHub repo james-thorson/FishStatsUtils@2.0.0

&

** testing if installed package keeps a record of temporary installation path
ERROR: hard-coded installation path: please report to the package maintainer and use '--no-staged-install'
* removing 'C:/Program Files/R/R-3.6.1/library/00LOCK-VAST/00new/FishStatsUtils'
Error: package or namespace load failed for 'VAST':
 .onAttach failed in attachNamespace() for 'VAST', details:
  call: NULL
  error: Failed to install 'FishStatsUtils' from GitHub:
  (converted from warning) installation of package 'C:/Users/NED~1.LAM/AppData/Local/Temp/Rtmpo1Up8z/file2a44784143/FishStatsUtils_2.0.0.tar.gz' had non-zero exit status
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Program Files/R/R-3.6.1/library/VAST'
Error: Failed to install 'VAST' from GitHub:
  (converted from warning) installation of package ‘C:/Users/NED~1.LAM/AppData/Local/Temp/RtmpcVZ5i1/file28c843b86bf1/VAST_3.0.0.tar.gz’ had non-zero exit status

**Comment by James-Thorson-NOAA** [comment]
please use 

```R
install_github("james-thorson/VAST", INSTALL_opts="--no-staged-install")
``` 

as it suggests on the main-page instructions, and report back if that doesn't fix it.
