### ISSUE TITLE
Error in make_spatial_info() FishStatsUtils 3.2 and VAST 3.2 - User extrapolation grid

### ISSUE THREAD

**Issue by oceanconner** [James-Thorson-NOAA/VAST#193]
Encountered an error using VAST 3.2 that does not arise using 3.1 with the same input. Other discrepancies: works on MRAN 3.5.3 but not on 3.5.1

Region= "user" with an extrap grid of 4 nmi^2 for the eastern Bering Sea.

**Executing code:**
 Spatial_List = make_spatial_info( n_x=n_x,  Method=Method, Lon_i=Data_Geostat[,'Lon'], Lat_i=Data_Geostat[,'Lat'], Extrapolation_List=Extrapolation_List, DirPath=DateFile, Save_Results=FALSE, fine_scale=F)

**Gives the following traceback:**
Error in rbind(info, getNamespaceInfo(env, "S3methods")) : number of columns of matrices must match (see arg 2)
11.
stop(e)
10.
value[[3L]](cond)
9.
tryCatchOne(expr, names, parentenv, handlers[[1L]])
8.
tryCatchList(expr, classes, parentenv, handlers)
7.
tryCatch(loadNamespace(name), error = function(e) stop(e))
6.
getNamespace(ns)
5.
asNamespace(ns)
4.
getExportedValue(pkg, name)
3.
INLA::inla.mesh.create
2.
Calc_Anisotropic_Mesh(Method = Method, loc_x = Kmeans$centers, loc_g = loc_g, loc_i = loc_i, Extrapolation_List 

= Extrapolation_List, fine_scale = fine_scale, ...)
1.
make_spatial_info(n_x = n_x, knot_method = "grid", Method = Method, Lon_i = Data_Geostat[, "Lon"], Lat_i = 

Data_Geostat[, "Lat"], Extrapolation_List = Extrapolation_List, DirPath = DateFile, Save_Results = FALSE, 

fine_scale = FALSE)

I am currently trying to have OFIS upgrade my VM to MRAN 3.5.3 to see if that makes the difference. I will report back.

**Comment by James-Thorson-NOAA** [comment]
The error is the same as #189. I'm closing here and feel free to follow up on that thread.
