### ISSUE TITLE
Update needed for plot_residuals in VAST--single-species_example.Rmd

### ISSUE THREAD

**Issue by oceanconner** [James-Thorson-NOAA/VAST#195]
The example code for VAST--single-species_example.Rmd plot_residuals() needs to be updated to reflect changes made in FishStatsUtils. I will reply back with the syntax when I get it to run.

**Comment by James-Thorson** [comment]
I don't maintain that example script, those are deprecated, please use the
wiki simple examples instead.

**Comment by oceanconner** [comment]
Oh, thanks!
