### ISSUE TITLE
crossval

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#198]
How do I specify the grid_size_km in the crossval R code? It seems to default to 25

**Comment by James-Thorson-NOAA** [comment]
It might be easier for others to re-read this seeing more details ;)

But I'm guessing you mean in the [simple example](https://github.com/James-Thorson-NOAA/VAST/wiki/Simple-example) specifically how to modify:

```R
# Make settings (turning off bias.correct to save time for example)
settings = make_settings( n_x=100, Region=example$Region, purpose="index", 
  strata.limits=example$strata.limits, bias.correct=FALSE )

# Run model
fit = fit_model( "settings"=settings, "Lat_i"=example$sampling_data[,'Lat'], 
  "Lon_i"=example$sampling_data[,'Lon'], "t_i"=example$sampling_data[,'Year'], 
  "c_i"=rep(0,nrow(example$sampling_data)), "b_i"=example$sampling_data[,'Catch_KG'], 
  "a_i"=example$sampling_data[,'AreaSwept_km2'], "v_i"=example$sampling_data[,'Vessel'] )
```

how to change the `grid_size_km` input when using `Region="Other"`.  There's two easy ways:

1.  Modify `settings` after assembly, inserting `settings$grid_size_km = 30`, between `make_settings(.)` and `fit_model(.)`;  OR

2.  Pass additional arguments, e.g., `grid_size_km` directly to `fit_model(.)` where it will over-ride defaults, i.e., `fit_model( ..., grid_size_km=30)`, see `?fit_model` for more details on argument passing.  This method of argument passing was started with `FishStatsUtils` V2.3.0 so please check your version before trying.

As always, its worth double-checking this and reporting back if there's a problem
