### ISSUE TITLE
In tutorial, TmbData gave error message, how to fix it?

### ISSUE THREAD

**Issue by darren321** [James-Thorson-NOAA/VAST#199]
> TmbData = make_data("Version"=Veersion, "FieldConfig"=FieldConfig,
"OverdispersionConfig"=OverdispersionConfig, "RhoConfig"=RhoConfig, "ObsModel"=ObsModel, "c_i"=as.numeric(Data_Geostat[,'spp'])-1, "b_i"=Data_Geostat[,'Catch_KG'], "a_i"=Data_Geostat[,'AreaSwept_km2'], "v_i"=as.numeric(Data_Geostat[,'Vessel'])-1, "s_i"=Data_Geostat[,'knot_i']-1, "t_i"=Data_Geostat[,'Year'], "a_xl"=Spatial_List$a_xl, "MeshList"=Spatial_List$MeshList, "GridList"=Spatial_List$GridList, "Method"=Spatial_List$Method, "Options"=Options )

Error in ifelse(is.null(spatial_list), 1, spatial_list$n_g) : 
  argument "spatial_list" is missing, with no default
In addition: Warning message:
In make_data(Version = Version, FieldConfig = FieldConfig, OverdispersionConfig = OverdispersionConfig,  :
   Consider changing use of `make_data` to include `spatial_list` as input

**Comment by James-Thorson-NOAA** [comment]
Those "VAST/examples" Rmd scripts are deprecated and I've just renamed them to be more clear in the development branch of VAST.  Please use high-level functions instead as documented here: https://github.com/James-Thorson-NOAA/VAST/wiki/Simple-example
