### ISSUE TITLE
Covariates effect

### ISSUE THREAD

**Issue by danielvilasgonzalez** [James-Thorson-NOAA/VAST#202]
Hi,

I am running a multispecies model to extract response functions of these species to depth covariate. The model converges and the outputs look like a good fit. But I have a problem when I try to extract the covariate effect (fit$ParHat$gamma1_ctp). This covariate effect always is the same (0.1) for each category and each year, and even if I modify or replace that covariate for another one, it computes always the same effect (0.1).  I tried other distributions, other factors, adding a covariate "formula"... but there is no change. Could anybody explain to me why? 

Thanks

**Comment by colemonnahan** [comment]
The way TMB models, like VAST, toggle estimation of certain parameters is through a "map" which basically tells the optimizer not to update the values of a parameter from its initial value. VAST uses initial values of 0.1 for covariate effects. So what must be happening is that the covariates are not being estimated inside the model (being mapped "off").

When VAST builds the model it prints a list of fixed and random effects. Does gamma1_cpt appear in that list? How about gamma2_ctp? The parameters listed in that section are what are being estimated, all other parameters are not. Maybe you can post how you specified your covariates in the model?

**Comment by danielvilasgonzalez** [comment]
Thanks for you feedback. When I print the parameter estimates ('fit$parameter_estimates$par'), gammas (neither gamma1_ctp nor gamma2_ctp) do not appear (only appear betas, loadings, logkappa and logsigma). Here is the code to build the model:

fit = fit_model( "settings"=settings, "Lat_i"=Data_Geostat[,'Lat'],
                 "Lon_i"=Data_Geostat[,'Lon'], "t_i"=Data_Geostat[,'Year'],
                 "b_i"=Data_Geostat[,'Catch_KG'],"test_fit"=TRUE,
                 "a_i"=Data_Geostat[,'AreaSwept_km2'],
                 optimize_args=list("getsd"=TRUE),'X_xj'=Data$X_xj,
                 "a_xl"=Spatial_List$a_xl, "MeshList"=Spatial_List$MeshList, 
                 "GridList"=Spatial_List$GridList,spatial_list = Spatial_List,
                 observations_LL = Data_Geostat[,c("Lat","Lon")],
                 "c_i"=as.numeric(Data_Geostat[,'spp'])-1,
                 getJointPrecision=TRUE,vars_to_correct="Index_cyl")

where Data$X_xj is a matrix including depth values for each knot.

**Comment by colemonnahan** [comment]
I don't think X_xj is an argument to that function so maybe it's just ignoring it and reverting to the default of no covariate effects. Try specifying them as in this example:

https://github.com/James-Thorson-NOAA/VAST/wiki/Specifying-covariates

**Comment by danielvilasgonzalez** [comment]
Thanks Cole. I already used the argument 'covariate_data' instead of X_xj, and I'm getting the same results when I'm using 'covariate_data', so there is no estimation on gammas

**Comment by danielvilasgonzalez** [comment]
I run the example on the wiki (https://github.com/James-Thorson-NOAA/VAST/wiki/Specifying-covariates), and I am not getting any estimates on gamma:

fit$parameter_estimates$par

https://github.com/James-Thorson-NOAA/VAST/wiki/Specifying-covariates

$par
    beta1_ft     beta1_ft     beta1_ft     beta1_ft     beta1_ft     beta1_ft     beta1_ft     beta1_ft     beta1_ft   L_omega1_z L_epsilon1_z 
  -0.8525137   -0.6168844   -0.5449449   -0.4910678   -0.2092676   -0.2036421   -0.2770123   -0.2657567   -0.8288912    1.8212048    0.2402518 
   logkappa1     beta2_ft     beta2_ft     beta2_ft     beta2_ft     beta2_ft     beta2_ft     beta2_ft     beta2_ft     beta2_ft   L_omega2_z 
  -4.5928280    2.0863608    2.1563636    2.1229203    1.9598793    2.3356374    2.3060948    2.4536891    2.1082528    1.9455151    0.3817044 
L_epsilon2_z    logkappa2    logSigmaM 
   0.3426867   -4.0543600    0.4676863

**Comment by James-Thorson-NOAA** [comment]
what does packageVersion.txt show?  I assume you need to update your version of VAST and FishStatsUtils

**Comment by danielvilasgonzalez** [comment]
It shows that:

Package: VAST
Type: Package
Title: Vector-autoregressive spatio-temporal (VAST) model
Version: 3.0.0

How can I update VAST and FishStatsUtils?

**Comment by James-Thorson-NOAA** [comment]
that's a question for a different forum, but feel free to re-open here if that Wiki example is still not working after updating.

**Comment by arregi1990** [comment]
Hi there, 
I take advantage of this post, to open again this issue. I'm especially interested in determining which coefficient I should check to know the impact of my covariates. In fact, the two gamma coefficients, gamma1 and gamma2, often show opposite signs in my case.

I have seen that in Table 2 of "Spatio-temporal variation in fish condition is not consistently explained by density, temperature, or season for California Current groundfishes" you only provide one coefficient per variable so I was wondering which one you used. 

Thanks
