### ISSUE TITLE
Error message with TmbList = VAST::make_model

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#205]
Just set up VAST on my new laptop with Windows 10, Microsoft Open R 3.5 and packages: FishStatsUtils-development,  INLA_18.07.12, TMB_contrib_R-master, TMBhelper, VAST-development, and utilities-master.

Getting an error message when running TmbList = VAST::make_model

> TmbList = VAST::make_model("TmbData"=TmbData, "RunDir"=DateFile, "Version"=Version, "RhoConfig"=RhoConfig, "loc_x"=spatial_list$loc_x, "Method"=spatial_list$Method)

c:/Rtools/mingw_64/bin/g++ -m64 -I"C:/PROGRA~1/MIE74D~1/ROPEN~1/R-35~1.3/include" -DNDEBUG -IC:/PROGRA~1/MIE74D~1/ROPEN~1/R-35~1.3/library/TMB/include -IC:/Users/ELLENY~1.VM/DOCUME~1/R/WIN-LI~1/3.5/RCPPEI~1/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_VAST_v8_3_0  -DTMB_LIB_INIT=R_init_VAST_v8_3_0     -I"C:/a/w/1/s/vendor/extsoft/include"     -O2 -Wall  -mtune=core2 -c VAST_v8_3_0.cpp -o VAST_v8_3_0.o
c:/Rtools/mingw_64/bin/g++ -m64 -shared -s -static-libgcc -o VAST_v8_3_0.dll tmp.def VAST_v8_3_0.o -LC:/a/w/1/s/vendor/extsoft/lib/x64 -LC:/a/w/1/s/vendor/extsoft/lib -LC:/PROGRA~1/MIE74D~1/ROPEN~1/R-35~1.3/bin/x64 -lR
Constructing atomic logspace_sub
Error in retape(set.defaults = TRUE) :
  Memory allocation fail in function 'MakeADFunObject'

**Comment by James-Thorson-NOAA** [comment]
Thanks for posting on the issue tracker, where we can keep a permanent record and others can search and read the response.

I am guessing that you are using `Region="Other"` and specifying an extrapolation-area that is too large relative to the default value for `grid_dim_km`.  
1.  Please try increasing the extrapolation-grid resolution i.e. `grid_dim_km=c(100,100)`
2.  Try checking the Lat and Lon bounds for the data you're including;  if it wraps around the date-line this likely causes a problem.

In the future this issue could be solved generically by:
* Developers making a new `Region="Other2"` that automatically detects a reasonable default resolution
* Developers switching from `PBSmapping` to `sp` to avoid problems with the dateline UTM conversion.

Please feel free to respond here with experience when trying these options 1-2, and close the issue when its solved.

**Comment by EllenY** [comment]
Thanks Jim. Your suggestion worked. 
1. I am using Region="Other".  I added the extrapolation grid resolution to make_extrapolation_info..

if( Region == "Other" ){
  Extrapolation_List = make_extrapolation_info( Region=Region, strata.limits=strata.limits, observations_LL=Data_Geostat[,c('Lat','Lon')],maximum_distance_from_sample=37,grid_dim_km=c(100,100) )
}

2. Lat and Lon do not wrap around the date line.

**Comment by EllenY** [comment]
Thank you

**Comment by ben-williams** [comment]
Getting the same error message when running the EBS_pollock example:
`Error in retape(set.defaults = TRUE) : 
  Memory allocation fail in function 'MakeADFunObject'`

Microsoft 10 - 16gb 
R: 3.6.2
Rtools 3.5
TMB: 1.7.16
VAST: v8_5_0


Compiles fine, tried changing the `n_x` and reducing the amount data with no luck.
