### ISSUE TITLE
Explanation of plot_anisotropy

### ISSUE THREAD

**Issue by cnotti** [James-Thorson-NOAA/VAST#210]
Are you able to explain how the plot_anisotropy function (https://rdrr.io/github/James-Thorson-NOAA/FishStatsUtils/src/R/plot_anisotropy.R) works?
 
Specifically, I don’t understand where the following come from/what they do,
 

```
rss = function(V) sqrt(sum(V[1]^2+V[2]^2))
 
Pos_Major = Eigen$vectors[,1]*Eigen$values[1] * Report$Range_raw1
Pos_Minor = Eigen$vectors[,2]*Eigen$values[2] * Report$Range_raw1
Pres_Major = Eigen$vectors[,1]*Eigen$values[1] * Report$Range_raw2
Pres_Minor = Eigen$vectors[,2]*Eigen$values[2] * Report$Range_raw2
 
rx=rss(Pos_Major)
ry=rss(Pos_Minor)
 
angle=-1*(atan(Pos_Major[1]/Pos_Major[2])/(2*pi)*360-90)
```

Thanks,
Chris

**Comment by James-Thorson-NOAA** [comment]
Thanks for posting the question on the issue tracker, where the question and response are searchable and transparent.

VAST estimates a linear transformation H and a decorrelation distance `Report$Range_raw1` and `Report$Range_raw2` that are calculated from estimated decorrelation rates `log_kapp1` and `log_kappa2`.  I then want to visualize the distance you have to go to get to 13% correlations.  I also want to use other software for plotting, i.e., `shape::plotellipse`, which requires as inputs the major and minor-axis distance and the angle of the major axis.  The rest is just trigonometry to calculate one from the other.
