### ISSUE TITLE
recenter plot_map for aleutian islands?

### ISSUE THREAD

**Issue by mkapur** [James-Thorson-NOAA/VAST#216]
I'm working with a fresh install of VAST and FishStatusUtils on R 3.6.2. Possibly related to #16 and/or #74 .   I am running a model which includes the Aleutian Islands and West Coast US. The default density plots are showing the whole world, likely to capture data across the AI. Is there an arg to plot_maps where I can auto-center on the NE Pacific, and include all of AK in each panel?
Thanks 
![density](https://user-images.githubusercontent.com/10951552/73679171-bb3e7180-466e-11ea-8f1c-3a0774c89975.png)

**Comment by James-Thorson-NOAA** [comment]
Please explicitly pass the projection you'd like to use.  For the North Pacific I have tried a few options:

```R
projargs_plot = "+proj=utm +datum=WGS84 +units=km +zone=3"
#projargs_plot = "+proj=moll +lon_0=-150 +datum=WGS84 +units=km"
#projargs_plot = "+proj=natearth +lon_0=-180 +datum=WGS84 +units=km"

plot_maps( ... , projargs=projargs_plot )
```

... and could you report back your experience on this thread?

**Comment by mkapur** [comment]
Thanks for your quick reply. My outcomes were as follows:
`projargs_plot = "+proj=utm +datum=WGS84 +units=km +zone=3"` 

Threw the following:
```Error in .spTransform_Polygon(input[[i]], to_args = to_args, from_args = from_args,  : 
  failure in Polygons 33 Polygon 17 points 1318:1319:1320:1321:1322:1323:1324:1325...etc

In addition: Warning message:
In .spTransform_Polygon(input[[i]], to_args = to_args, from_args = from_args,  :
  210 projected point(s) not finite
```
`projargs_plot = "+proj=moll +lon_0=-150 +datum=WGS84 +units=km` ran, and the coordinate range looks OK but the resultant plot was distorted:
![ln_density](https://user-images.githubusercontent.com/10951552/73682598-82ee6180-4675-11ea-8ff9-e11223c19dff.png)

And `projargs_plot = "+proj=natearth +lon_0=-180 +datum=WGS84 +units=km"` presented the same banding:
![ln_density](https://user-images.githubusercontent.com/10951552/73682795-f6906e80-4675-11ea-8aca-b80a1aa98751.png)

Neither this nor the previous threw a warning. It seems that the underlying data are showing up alright, but the land masses themselves are having issues? Let me know if I should provide addl info. FWIW the data_by_year plot, for which I did not specify a projection, looks alright: 
![Data_by_year](https://user-images.githubusercontent.com/10951552/73682936-2dff1b00-4676-11ea-8482-c835e27f5a55.png)

Thanks!

**Comment by Cole-Monnahan-NOAA** [comment]
FWIW I have run across this many times in the NP. I found using the "world2" dataset which is centered on Pacific is a good thing to try. I haven't looked into the code for this plotting but it probably would require shifting the coordinates. If you look at the help it now helpfully says this:

This data set is in fact largely obsolete. Often the same (more general) result can be obtained by using wrapping:

````map("world", wrap=c(0,360))````

This will also work fine with `fill=TRUE` or any other appropriate longitude interval (e.g. c(-90,270)).

However, world2 is useful when setting xlim to an interval crossing the 180 meridian.

**Comment by James-Thorson-NOAA** [comment]
map( "world2" ) isn't eary to access with the new `sp` interface.  I agree its a good fix for other uses, or when exporting results.

If you're using the latest VAST version please next try:

```R
projargs_plot = "+proj=utm +datum=WGS84 +units=km +zone=3"
#projargs_plot = "+proj=moll +lon_0=-150 +datum=WGS84 +units=km"
#projargs_plot = "+proj=natearth +lon_0=-180 +datum=WGS84 +units=km"

plot_maps( ... , projargs=projargs_plot, country=c("united states of america","canada","mexico","russia") )
```
 
and perhaps play around with which countries are included.  And of course please report back!

**Comment by mkapur** [comment]
Awesome -- specifying the countries worked to create a correct map. 
Thanks to you both for your speedy help!

```
projargs_plot = "+proj=utm +datum=WGS84 +units=km +zone=3"
plot_maps( ... , projargs=projargs_plot, 
country=c("united states of america","canada","mexico","russia") )
```

![2020-01-23_nx=500_Triennial_WCGBTS_BCs_BCo_AK_DOM_LL_GOA_baseQ=AK_DOM_LL1980_2018ln_density](https://user-images.githubusercontent.com/10951552/73684172-80413b80-4678-11ea-91d1-cfe94ac74046.png)

**Comment by James-Thorson-NOAA** [comment]
Thanks for posting the issue!

Would you be willing to send a few minutes to some edits (either via email or pull request) to `plot_variable` or `plot_maps` to improve documentation for this?  I have trouble figuring out how to improve docs and would welcome the feedback.

**Comment by mkapur** [comment]
Yes - I will put it on my calendar for this week. Likely I'll give pointers
to the projargs specifications in the help file (where I looked first).
Thanks
MK
