### ISSUE TITLE
Error: (converted from warning) package 'TMB' was built under R version 3.6.2

### ISSUE THREAD

**Issue by sean-rohan** [James-Thorson-NOAA/VAST#219]
I've encountered the following error when trying to install VAST. I had to install dependencies individually to reach this point. Any idea how to get around this issue?

Installing package into ‘C:/Users/sean.rohan/Work/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'VAST' ...
** using non-staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'TMB' was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package 'VAST'
* removing 'C:/Users/sean.rohan/Work/R/win-library/3.6/VAST'
Error: Failed to install 'VAST' from GitHub:
  (converted from warning) installation of package ‘C:/Users/SEAN~1.ROH/AppData/Local/Temp/RtmpW834IL/file1f5432382a68/VAST_3.3.0.tar.gz’ had non-zero exit status

**Comment by James-Thorson-NOAA** [comment]
Sean,

It appears that `install.packages("TMB")` is causing the error.  Can you confirm?

If yes, then could you try exploring `options` to eliminate the setting you have on that's changing warnings to errors?

**Comment by colemonnahan** [comment]
You need the latest R version. Contact IT ASAP and ask them to remotely
update it on your NOAA laptop (or if personal do it yourself).

**Comment by sean-rohan** [comment]
Jim, the error occurred after installing TMB. Cole's solution worked, it was a version issue (R 3.6.1, TMB built in 3.6.2).

Thanks!

**Comment by James-Thorson-NOAA** [comment]
Thanks Sean!  

For others reading this, I suspect that there's other workable solutions, including (1) using an older version of TMB from the previous github releases, or (2) ignoring the warning-turned-error in Options.

Jim

**Comment by Cole-Monnahan-NOAA** [comment]
It looks like this can be a temporary solution:

`Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)`

Then do the installation. I haven't checked this but found a solution online for this error.

**Comment by CaitlinAkselrud-NOAA** [comment]
> It looks like this can be a temporary solution:
> 
> `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)`
> 
> Then do the installation. I haven't checked this but found a solution online for this error.

Currently running `install_github("james-thorson/VAST", R_REMOTES_NO_ERRORS_FROM_WARNINGS="true", INSTALL_opts="--no-staged-install")` results in the following error: 
`Error: Failed to install 'VAST' from GitHub:
  (converted from warning) installation of package ‘.../file3770f046be4/VAST_3.6.1.tar.gz’ had non-zero exit status
Error: `msg` has been renamed to `message` and is deprecated as of rlang 0.3.0`

Currently using R 4.0.2, and latest version in R 4.0.3.
