### ISSUE TITLE
Definition of Npool

### ISSUE THREAD

**Issue by ceciliaOLearySBU** [James-Thorson-NOAA/VAST#220]
What is the definition of 'Npool' argument in make_model() 
(used in multivariate examples, [age-comps expansion](https://github.com/James-Thorson-NOAA/VAST/wiki/Expand-age-and-length-composition)))

**Comment by James-Thorson-NOAA** [comment]
It pools hyper-variances (sigmaM and Ls) for categories that have fewer than `Npool` total observations in the entire data set.  This is to avoid situations where you have as many hyper-variance parameters as observations for a given category, which then is a type of "saturated" model. Feel free to keep asking questions here, although I will close the issue for now.

**Comment by ceciliaOLearySBU** [comment]
Is this pooling when categories have few observations than total observations across years or across space?

**Comment by James-Thorson-NOAA** [comment]
Hyperparameters are constant across space, so the only way to pool them to increase information per parameter is across time (which is what it does).

**Comment by ceciliaOLearySBU** [comment]
Perfect, thanks for clarifying
