### ISSUE TITLE
dplyr/tidyverse and VAST

### ISSUE THREAD

**Issue by jysullivan** [James-Thorson-NOAA/VAST#222]
Just an FYI that VAST doesn't take kindly to tibbles. If you use dplyr functions to clean up your data, add an `as.data.frame()`:

For example:

```
sampling_data <- my_data %>% 
  ungroup() %>% 
  distinct(cpue, year, Vessel, end_lat, end_lon) %>% 
  select(Catch_KG = cpue, Year = year, Vessel, Lat = end_lat, Lon = end_lon) %>% 
  mutate(AreaSwept_km2 = 1) %>% 
  as.data.frame()
```

**Comment by Cole-Monnahan-NOAA** [comment]
I was unable to recreate this in the latest version. It's true that if you extract a column from a tibble like `dat[,'Lat']` it is still a tibble. Interestingly if it is `dat$Lat` it is a numeric vector. But `FishStatsUtils::fit_model` does this:

`data_frame = data.frame( "Lat_i"=Lat_i, "Lon_i"=Lon_i, "a_i"=a_i, "v_i"=v_i, "b_i"=b_i, "t_i"=t_iz, "c_iz"=c_iz )`

and this conversion happens smoothly to a data.frame even if the data vectors are tibbles. I'm guessing that something changed on the tibble side.

Thanks for posting this warning, as data wrangling as tibbles will continue to gain popularity and `fit_model` needs to be robust to this and other formats. 

Closing. Please reopen if I'm missing something...?
