### ISSUE TITLE
Simulator EMs not converging

### ISSUE THREAD

**Issue by Charles-Adams-NOAA** [James-Thorson-NOAA/VAST#224]
Recently edited Simulator code runs fine all the way through to test for hyper-stability and bias in average (both close to 1). However, if you insert the following lines into the EM loop it reveals that the EMs aren't converging:

if ("The model is likely not converged" %in% fit_sim$parameter_estimates$Convergence_check) {
  write.csv(fit_sim$parameter_estimates$Convergence_check, paste0("check.convergence.EM", rI, ".csv"))
}

**Comment by James-Thorson-NOAA** [comment]
My guess is that the final gradients are too high for the overly cautious check built into fit_tmb. Please try running with an increased value for newtonsteps and report back on this thread?

**Comment by Charles-Adams-NOAA** [comment]
Increasing newtonsteps appears to have resolved convergence issues
