### ISSUE TITLE
Compilation error of VAST_v9_2_0.cpp by TMB::compile

### ISSUE THREAD

**Issue by yukio-takeuchi** [James-Thorson-NOAA/VAST#228]
On Ubuntu 18.04 with gcc 7.5 
```
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
```
and 
on Mac OS 10.15.4 with gcc 9.3
```
gcc version 9.3.0 (Homebrew GCC 9.3.0)
```
The command TMB::compile("VAST_9_2_0.cpp") failed with following error on L2143
```
VAST_v9_2_0.cpp:2143:40: error: call of overloaded ‘abs(double)’ is ambiguous
               overlap_z(z) -= 0.5 * abs( (Index_gcyl(g,overlap_zz(z,0),overlap_zz(z,1),0)/Index_cyl(overlap_zz(z,0),overlap_zz(z,1),0)) - (Index_gcyl(g,overlap_zz(z,2),overlap_zz(z,3),0)/Index_cyl(overlap_zz(z,2),overlap_zz(z,3),0)) );
                                     ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I do not know if it is optional solution but 
If abs in L2143 is related with fabs, compilation finished without error.

**Comment by James-Thorson-NOAA** [comment]
Thanks for pointing out the issue on Linux and MacOS (I'm obviously a windows user and Travis-CI hasn't been working recently for cross-platform testing), and also suggesting a fix.  

I switched abs(.) to fabs(.) on the master branch.  Could you please download, test again, and confirm that its now compiling for you?

Once you do this, I'll then do release 3.4.1 as a hot-fix

**Comment by yukio-takeuchi** [comment]
Great! Now both on MacOS and Ubuntu no compilation error occurred. 
Thank you for your quick work.
