### ISSUE TITLE
Add sample station locations to FishStatsUtils::plot_maps

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#229]
Hi,
Is there a way to add black dots for station locations to the contour plots of log-prediction density within the FishStatsUtils::plot_maps function?
Thank you
Ellen

**Comment by James-Thorson-NOAA** [comment]
Ellen,

For detailed control, I recommend using `plot_variable(.)`, which is the plotting function used within `plot_map`.  You can do:

```R
plot_variable( Y_gt=[matrix-with-one-column-for-thing-to-plot], add=TRUE, Format="" , ... )
```

to do each panel individually and then use `points` to add the sample locations yourself.  Please consider asking for example code from other VAST users, and then I could help if necessary.

**Comment by ceciliaOLearySBU** [comment]
I [really quickly...] adjusted the plot_variable function on my fork to be able to add in station points: [](https://github.com/ceciliaOLearySBU/FishStatsUtils/blob/master/R/plot_variable_with_stations)

with some sample code to run it: [](https://github.com/ceciliaOLearySBU/FishStatsUtils/blob/master/add_stations_to_density_map)

after Ellen's inquiry.

It's not incorporated into the rest of FishStatsUtils, you need to manually specify station data using Station_Data argument (with columns 'Lon' and 'Lat) and station.years = Year_Set[tI]. You can also alter the size of station points by altering 'cex.stations' (default set to 1 right now).

**Comment by EllenY** [comment]
Thank you both!
