### ISSUE TITLE
Spatial distribution of knots

### ISSUE THREAD

**Issue by mkajanus** [James-Thorson-NOAA/VAST#230]
Hi Jim,

I have spatially unevenly distributed data. This leads to a great variety of distances between the data points and the spatial knots they are associated with (some points are very close to the knot and some very far). Unfotunately, due to computational restrictions we can not increase the number of spatial knots, which would be the first way of trying to overcome this issue.

You have mentioned in your Guidance for decisions using VAST -paper (Fisheries Research, 2019; end of section 4.5) that there could be a possibility to place the knots of the spatial mesh evenly over the spatial domain instead of distributing the knots in relation to the available data points (more knots where data is distributed dense, leads to longer knot-point distances at regions with sparse data). Is this option/function available in current VAST and where could I find the Rhelp- or other documentation for it?

Or should I explore using Grid -method instead of Mesh?

Thank you for your help in advance.
Best,
Mira

**Comment by James-Thorson-NOAA** [comment]
I can't remember what release number added it, but recent releases of `FishStatsUtils` include this option easily.  Please explore `make_spatial_info( ..., knot_method="grid")`.  This option is also available via `fit_model( ..., knot_method="grid")`

**Comment by mkajanus** [comment]
Thank you for the advice. I will look into that.

Mira
