### ISSUE TITLE
Advice on using simulate_data

### ISSUE THREAD

**Issue by ACharsley** [James-Thorson-NOAA/VAST#231]
I'm currently working on a simulation study with VAST and I was wondering if I could get advice on using simulate_data. 

I would like to simulate data that represents three different sampling scenarios. These scenarios would be data sets of different sizes which represent sampling across the spatial domain (e.g. 25%, 50% and 75% random coverage of the spatial domain (in my case a stream network)). Is it possible to use simulate_data or Obj$simulate() to simulate data with different spatial coverage and sample sizes?

I’m also having issues with the OM. Under “types” 1 and 3 of simulate_data, simulations (of count data) are mostly zero (with a few non-zero counts) but under type 2 simulations seem more reasonable. Do you know why I’m getting this under types 1 and 3 (or what it's indicating about the OM) but not when I’m simulating new random effects (type 2)?

Thanks!

**Comment by James-Thorson-NOAA** [comment]
A few potential cases:

1.  for subsampling from your real-world design just use` simulate_data` and then exclude resulting samples by hand e.g. using `sample`
2.  for simulating a new design, fit the data using `PredTF_i` to indicate dummy data, which are then simulated by `simulate_data` and again exclude some by hand.

the different types have different expectations, particularly when treating intercepts as random effects.  So they'll typically have different proportions of zeros.  that's as much as I can say without knowing specifics.

**Comment by ACharsley** [comment]
Thanks Jim! :)
