### ISSUE TITLE
simulator throwing errors for model fit with VAST_V8_0_0

### ISSUE THREAD

**Issue by mkapur** [James-Thorson-NOAA/VAST#232]
I'm working with the example of the simulator here: https://github.com/James-Thorson-NOAA/VAST/wiki/Simulator. If I understand correctly, this functionality should work for models fit with any version > 4_4_0, and I should not need to re-fit my model if I already did so. 

I have an executed VAST model for which I saved the `Obj`, `Opt `and other things in an .Rdata format which I loaded into my workspace, but am getting the following error. FWIW, the same error is returned when I call  `TMBhelper::Optimize( obj=Obj )`. I recognize that some of the function calls in the wiki example are deprecated. I am not sure if this is a versioning issue, or something with my model itself. As a sanity check I re-ran my entire model using fit_tmb sucessfully.

Thanks!
```
Obj <- Save$Obj ## Save is a list
Sim = Obj$simulate( complete=TRUE )

Error in .Call("MakeDoubleFunObject", data, parameters, reportenv, PACKAGE = DLL) : 
  "MakeDoubleFunObject" not available for .Call() for package "VAST_v8_0_0"
```

**Comment by James-Thorson-NOAA** [comment]
I'm not sure; what error is pretty generic.  `simulate` requires that the DLL be linked to the object:  can you confirm that you are running this right after building and running the model (e.g., calling `fit_model`) or are you loading a previous save (where the latter won't work).

**Comment by mkapur** [comment]
Ah that must be it -- I was loading a previous save. I will re-build and re-run and update on the outcome. Thanks for the quick reply.

**Comment by James-Thorson-NOAA** [comment]
Do you know how I can add a line to the simulator to check whether a DLL or TMB object is loaded?  Would you be interested in doing some quick digging to see if there's a function in R to return TRUE/FALSE for a check like this?

**Comment by mkapur** [comment]
Sure, I can take a look, will let you know.

**Comment by mkapur** [comment]
OK, cursory digging yielded two potential options:
1) Check for a DLL in the working_dir specified by user:
`rlang::is_empty(list.files(working_dir , pattern = "*.dll")) ## returns FALSE if DLL not there`
2) Confirm that `Opt` in the environment is of class `fit_model`, or at least not a list. My understanding is that once it's saved and loaded it becomes a list, but only retains class `fit_model` just after being run. The downside is we assume their fitted model is indeed called `Opt`, but that could be accounted for:
```
class(Opt) == "fit_model"
class(Opt) != "list"
```
I admit the wiki confused me about exactly which call one should make to generate the simulated data: is it the `Sim = Obj$simulate( complete=TRUE )` call at the top, or the `Data_sim = simulate_data( fit_orig, type=Type )` nested within the Pollock example?

**Comment by Cole-Monnahan-NOAA** [comment]
FYI there is this function which is probably similar to what you want:

TMB:::getUserDLL

https://github.com/kaskr/adcomp/blob/master/TMB/R/TMB.R#L39

**Comment by mkapur** [comment]
@Cole-Monnahan-NOAA That is pretty sweet, thanks!
My base model takes 20+ hrs to run so I will have to check tomorrow if I was able to get the simulate call to work.

**Comment by James-Thorson-NOAA** [comment]
You know to try Microsoft Open R for parallelization?  

Also, there's a new feature in the latest release, which reduces the number of extrapolation-grid cells using `make_settings( ..., max_cells=10000)` for 10,000 extrapolation-cells.  Have you explored that for speeding up your runs across survey areas?

**Comment by James-Thorson-NOAA** [comment]
OK, I've added code inspired by `TMB:::getUserDLL` to provide an informative error message if using `simulate_data` when the DLL is not linked.
