### ISSUE TITLE
make_data, F_ct has wrong dimensions

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#234]
Hi,
make_data is tossing an error,

Error in VAST::make_data(b_i = Data_Geostat[, "Catch_KG"], a_i = Data_Geostat[,  : 
  `F_ct` has wrong dimensions

I am wondering if it is because I am missing one year of data (2008) in the time series 2004-2018 (specified as n_t=15). I have 6 species n_c=6 in the northern Bering Sea. I a missing the 2008 year for the 2004-2018 time series. n_t is being specified as 15.

#In the make_data code:   F_ct = matrix(0, nrow = n_c, ncol = n_t)
Here is what I specified.

TmbData <- VAST::make_data(
                              "b_i"=Data_Geostat[,'Catch_KG'], 
                              "a_i"= Data_Geostat[,'AreaSwept_km2'],
                              "t_iz"= Data_Geostat[,'Year'],
                              "c_iz" =as.numeric(Data_Geostat[,'spp']),
                              "e_i" = c_iz, 
                              "v_i" = as.numeric(Data_Geostat[, "Vessel"]), 
                              "FieldConfig"=c(6,6,6,6), 
                              "spatial_list"=Spatial_List, 
                              "ObsModel_ez" = c(10, 2), 
                              "OverdispersionConfig" = c(0, 0), 
                              "RhoConfig" = c( 0, 0, 0, 0), 
                              "VamConfig" = c(0,0,  0), 
                              "Aniso" = TRUE, 
                              "PredTF_i"= 1, 
                              "Xconfig_zcp" = NULL, 
                              "covariate_data" = NULL, 
                              #formula, 
                              "Q_ik" = NULL, 
                              "Network_sz" = NULL, 
                              "F_ct"= matrix(0, 6, 15), 
                              "F_init" = 1, 
                              "t_yz" = NULL, 
                              "CheckForErrors" = TRUE, 
                              "yearbounds_zz" = NULL, 
                              "Options" = Options, 
                              "Expansion_cz" = NULL, 
                              "Z_gm" = NULL, 
                              "Version" = FishStatsUtils::get_latest_version(package = "VAST"), 
                              "overlap_zz" = matrix(ncol = 6, nrow = 0))

**Comment by James-Thorson-NOAA** [comment]
Please try leaving out argument `F_ct` to `make_data` and let it fill in the default value.

**Comment by EllenY** [comment]
same error without the argument F_ct

**Comment by James-Thorson-NOAA** [comment]
OK, next try putting in "F_ct"= matrix(0, 6, 16)

**Comment by EllenY** [comment]
same error with:
"F_ct"= matrix(0, 6, 16)
"F_ct"= matrix(0, 6, 15)
"F_ct"= matrix(0, 6, 14)

**Comment by EllenY** [comment]
Using c_iz=as.numeric(Data_Geostat[,'spp'])-1 seemed to fix the issue when using the updated wrapper function fit_model()
