### ISSUE TITLE
Covariates effect via AIC

### ISSUE THREAD

**Issue by aastarloa** [James-Thorson-NOAA/VAST#236]
Hi, 
I'm trying to determine the effects that covariates (e.g. Chl, Temperature) have on my species spatio-temporal patterns by looking at the AIC score (similar to what is done in "Spatio-temporal variation in fish condition is not consistently explained by density, temperature, or season for California Current groundfishes" paper). 

By now, I have succesfully run a model with no covariates and with them using the following configuraton:
settings$FieldConfig = c("Omega1"=1, "Epsilon1"=1, "Omega2"=1 ,"Epsilon2"=1) 
settings$RhoConfig = c("Beta1"=3, "Beta2"=3, "Epsilon1"=4, "Epsilon2"=4) 

My question is if that configuration is appropiate when looking at the covariates effect or if some of them should be switched off.

Thanks

**Comment by Cole-Monnahan-NOAA** [comment]
Those settings are compatible with using AIC to select among covariates. The FieldConfig is specifying the spatial structure and the RhoConfig the temporal smoothing on annual intercepts (beta) and spatiotemporal terms (epsilon). Those components are distinct from the covariate terms, so if you leave those the same and change the covariate structure that is valid (technically those would be nested models too).

You could check this by putting in white noise covariates (AIC should not select them), or taking your fitted model and simulating data from it conditioned on meaningful covariate effects and then refit and see if AIC selects them.

**Comment by aastarloa** [comment]
Great! Many thanks

**Comment by aastarloa** [comment]
Hi, 
coming back to this, one new doubt:  comparing AIC between models, does provide infomation on the importance of a given covariate over density estimates (as we are modelling counts/densities) or also over derived quantities such as the centre of gravity?

Or maybe, for this second aim another approach would be better?

Thanks

**Comment by Cole-Monnahan-NOAA** [comment]
Model selection tools like AIC give importance of covariates for explaining the data, not derived quantities like density or center of gravity. Note that the "data" in VAST are the b_i inputs which can be counts or catches in kg or whatever.

The use of AIC in VAST is no different than any other statistical modeling platform. VAST is just a complicated model. I suggest reading up on AIC and other tools if you're still unsure how to use them. Like I mentioned above there are some experiments you could run that might help understand AIC in the context of VAST.

**Comment by James-Thorson-NOAA** [comment]
As an alternative to AIC, a person can instead "zero out" the estimated influence of a single process and calculate the decrease in variance-explained when doing so for each process.  This provides a "variance explained" for each individual process, but does not provide a metric of "statistical significance".  This was demonstrated here: https://doi.org/10.1111/faf.12225, although code to do so automatically using VAST has not been maintained.  FWIW

**Comment by aastarloa** [comment]
Thanks to both. Following the example you mention Jim, I have fitted:
a) a spatio-temporal model, with spatial and spatio-temporal variation 
b) a temperature-based model, maintaining the spatial variation but switching off the spatio-temporal variation, so all the variation could be attributed to temperature. Is this correct?
Then, when I plot the CoG obtained from both models, it can be easily seen that temperature contributes slightly to the variation  observed with no covariates. But how can I get the deviance explained? 
![Eastings](https://user-images.githubusercontent.com/50455690/89162004-b605a500-d573-11ea-932b-9dfd8e16d18e.png)

**Comment by James-Thorson-NOAA** [comment]
yeah, that looks like what was also seen here (https://doi.org/10.1016/j.fishres.2019.03.006), although spatially varying responses might explain more via temperature (https://doi.org/10.1002/lno.11238).  And sorry, no, deviance explained is a complicated topic and I can't help.

**Comment by aastarloa** [comment]
Sorry, I meant variance-explained, following what you were saying above.
