### ISSUE TITLE
Crossvalidate_Fn missing in FishStatsUtils version 2.6.0

### ISSUE THREAD

**Issue by bchasco** [James-Thorson-NOAA/VAST#237]
Hi Jim, 

I see Crossvalidate_Fn is still in the help menu but the function does not seem to be included in the package version 2.6.0. Has it been deprecated and or combined with another function?

Thanks,
Brandon

**Comment by James-Thorson-NOAA** [comment]
The code still lives in deprecated.R, and can be accessed using FishStatsUtils:::Crossvalidate_Fn(.).  I don't maintain it, but the code could be a useful guide and I'd welcome a pull request to update it if needed.
