### ISSUE TITLE
Wiki example for fish condition/density

### ISSUE THREAD

**Issue by sean-rohan** [James-Thorson-NOAA/VAST#238]
The Wiki example for the joint model for fish condition and density does not work:

> example = load_example( data_set = "goa_arrowtooth_condition_and_density" )
Error in na.omit(sampling_data) : object 'sampling_data' not found

https://github.com/James-Thorson-NOAA/VAST/wiki/Correlations-between-fish-condition-and-density

**Comment by James-Thorson-NOAA** [comment]
Could you try downloading the development branch of FishStatsUtils?   I'm pretty sure the problem was fixed on that branch.  Are you using the latest numbered release, or what other version?

**Comment by sean-rohan** [comment]
Thanks, Jim. Got the example running using the development branches of VAST and FishStatsUtils.

**Comment by agruss2** [comment]
Note that it should be: 
example = load_example( data_set = "GOA_arrowtooth_condition_and_density" )
I just corrected for that.
