### ISSUE TITLE
response plots of covariates effect

### ISSUE THREAD

**Issue by aastarloa** [James-Thorson-NOAA/VAST#240]
Hi, 
I am running models incorporating covariates and I was wondering if there is a way to get some reponse plots like those you get when using glm or gam (example below: how species abundance changes with distance from coast).
Thanks
![imagen](https://user-images.githubusercontent.com/50455690/85710038-248a5400-b6e6-11ea-86d2-b4365ec6e383.png)

**Comment by James-Thorson-NOAA** [comment]
what function are you using for producing that plot?

Currently there's no automated functionality for this type of plot, and no immediately plans to add it, but I'm happy to learn more.

**Comment by aastarloa** [comment]
Ok, thanks anyway. Answering to your question, plot or plotmo functions can give you plots like that after having fitted a glm or a gam.

**Comment by Cole-Monnahan-NOAA** [comment]
These types of plots make a lot of sense for looking at the effect of smoothers. Are you using smoothers on covariates in VAST or just linear effects? 

If the former, I wonder if you could create a predict data frame where you hold levels of all covariates constant (at e.g., mean) and pick a representative spot in space and time, varying only the effect you care about over a reasonable range and predicting? That'd be easy to do to get predictions (you could rbind it onto the real data with NA values for "b"). But what you'd really want is the standard error from an ADREPORT variable so you have the confidence intervals. I'm not sure how to do that without hacking VAST a bit. I know with backfitting algorithms used by GAMS they fit one variable at a time so these plots are a natural output. Maybe if you could find example code to take fitted smoothers and make these we could adapt them.

If it's linear presumably you could find a formula to make marginal effect plots. I don't know it off the top of my head or how but you could start at a place like https://cran.r-project.org/web/packages/sjPlot/vignettes/plot_marginal_effects.html. It's easy to extract the value and SE for the covariate effects so you'd just have to find a way to put them into something like that.

**Comment by Cole-Monnahan-NOAA** [comment]
I had a quick chat with Jim and there is some interest in a general solution. I think especially for smoothers this would be really helpful. After some quick googling I think this package is most promising:  

https://github.com/strengejacke/ggeffects/ 
https://joss.theoj.org/papers/10.21105/joss.00772  

The advantage here is we could either recreate the code in FishStatsUtils, or create a generic method for VAST and do a pull request to get it added. 

For example, here's one for GAMLSS which allows for smoothers on two model components (e.g., mean and variance) and so sort of resembles VAST: https://github.com/strengejacke/ggeffects/blob/master/R/get_predictions_gamlss.R 

I bet some of the other methods are close to VAST in terms of how to calculate the prediction data frame. Gonna be a little bit tricky with the delta model part. Once the predictions are sorted out the rest would be easy I think.

**Comment by James-Thorson-NOAA** [comment]
I'm adding this to a new Wiki page tracking outstanding development requests and ideas: https://github.com/James-Thorson-NOAA/VAST/wiki/Development-priorities

**Comment by aastarloa** [comment]
Many thanks to both. I will dig into it.

**Comment by James-Thorson-NOAA** [comment]
I've been exploring the use of package `effects` for another project and it looks promising (it only requires the formula and data frame of predictors, so its very fast).  An alternative is partial dependence plots (using package `pdp`) but that requires a predict function is therefore more error-prone given the current VAST implementation. 

I still have some hurdles to resolve before fully endorsing `effects` as the path forward.  I welcome any further thoughts on this thread, either upvoting the importance of providing updates on alternatives.

**Comment by Cole-Monnahan-NOAA** [comment]
Wow time flies. I think this would be a really valuable addition to VAST. Let me know if I can help test it. Would the effects package work for splines too?

**Comment by James-Thorson-NOAA** [comment]
Yeah, it works for `bs` for basis-splines, `:` for interaction terms, using `poly` for polynomial basis expansion etc.  Pretty much anything applicable in a formula.

I'd love some help resolving an issue with scoping and environments given multiple formula.  Its a pretty technical issue.  please email me directly if you want to talk it through

**Comment by James-Thorson-NOAA** [comment]
I have just added a somewhat experimental version of this feature using package `effects` on the development branch, as demonstrated on the [Wiki example](https://github.com/James-Thorson-NOAA/VAST/wiki/Specifying-covariates).  I welcome feedback on this thread.

**Comment by James-Thorson-NOAA** [comment]
I have just added a second option for visualizing marginal response curves (a.k.a. partial dependence plots), and both are contrasted on a new [Wiki page](https://github.com/James-Thorson-NOAA/VAST/wiki/Visualize-covariate-response).  I welcome feedback or suggestions on this thread, but I'm closing it for now.

**Comment by aastarloa** [comment]
Hi Jim,
Sorry for not answering before. I have been trying to run the example in another PC but I'm having problems to install the development branch. But I will keep trying.
Best,
Amaia

De: Jim Thorson <notifications@github.com>
Enviado el: lunes, 18 de enero de 2021 17:05
Para: James-Thorson-NOAA/VAST <VAST@noreply.github.com>
CC: Amaia Astarloa Diaz <aastarloa@azti.es>; Author <author@noreply.github.com>
Asunto: Re: [James-Thorson-NOAA/VAST] response plots of covariates effect (#240)


I have just added a second option for visualizing marginal response curves (a.k.a. partial dependence plots), and both are contrasted on a new Wiki page<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJames-Thorson-NOAA%2FVAST%2Fwiki%2FVisualize-covariate-response&data=04%7C01%7Caastarloa%40azti.es%7Ccbf6be19342547dae18408d8bbcac948%7C6219f1193e794e7facdea5750808cd9b%7C0%7C0%7C637465826941414143%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IslwVI%2FvpiIgUCij5lTR0rAW4sQXx3CwCxKCdfCn8ow%3D&reserved=0>. I welcome feedback or suggestions on this thread, but I'm closing it for now.

-

**Comment by aastarloa** [comment]
Hi, 
I explored the options on wiki, but with no success:
1) The line "covariate_data = data.frame( "Lat"=0, "Lon"=0, "Year"=example$covariate_data[,'Year'],
  "CPE"=(example$covariate_data[,'AREA_SUM_KM2_LTE2']-100000)/100000)" gave me problems with the pollock example, so I loaded "covariates_example", which already has a covariate_data. So, in the followng I use BOT_DEPTH as covariate and specify example$covariate_data[,"Year"]=NA to be able to continue. But,
2) The approach with effects package says that ""Effect.fit_model" function could not be found.
3) The approach with pdp, when running partial, says that "Error in predict.fit_model (x=object, Lat_i=object$data_frame$Lat_i, : unused arguments (new_covariate_data=newdata, do_checks =FALSE)
I am using the 3.6.1 version.

**Comment by aallyn** [comment]
Hello, I had been working through the wiki example recently, too, so figured I would chime in if it helps. The example needs the most recent development branch of VAST installed -- v3.7.0 I think this should also update FishStatsUtils to v2.9.0, which is also needed for the example to run. Hope that helps!

**Comment by aallyn** [comment]
For anyone interested, I did a quick comparison fitting b-splines in VAST with the `splines::bs()` formulation and subsequent plots from `Effect.fit_model` with an identical model fit with mgcv::gam b-splines and the plot returned by mgcv::plot.gam. The results and plots of the fitted smooths seem to be nearly, if not entirely, identical using the b-spline basis with `m = c(3,2)` in the mgcv::gam formulation, indicating a standard cubic regression spline with a penalty on the second derivative (curvature) of the fitted smooth. Figure below shows quick visual comparison, and code attached (.txt file) with some more details/information, building off the [Adding Covariates wiki example](https://github.com/James-Thorson-NOAA/VAST/wiki/Specify-covariates-and-visualize-responses).


![image](https://user-images.githubusercontent.com/6697903/106802481-064be580-6631-11eb-8f37-3fe2f7baa24a.png)

[VASTBSsplines_vs_mgcv.txt](https://github.com/James-Thorson-NOAA/VAST/files/5921184/VASTBSsplines_vs_mgcv.txt)
