### ISSUE TITLE
non-reproducible convergence issue in sequential calls to fit_model

### ISSUE THREAD

**Issue by afredston** [James-Thorson-NOAA/VAST#243]
I am using the code below on a long list of species from multiple regions, running in parallel. I'm encountering a really bizarre behavior where if I run the entire chunk for a given species, sometimes I get this error at the end, meaning each attempt to get the model to converge failed:

```
Error in par[-random] <- x : replacement has length zero
In addition: Warning message:
In (function (obj, fn = obj$fn, gr = obj$gr, startpar = obj$par,  :
  Hessian is not positive definite, so standard errors are not available
Error in `*tmp*`$parameter_estimates : 
  $ operator is invalid for atomic vectors
```

But then if I "manually" run VAST for the same species by running each call to fit_model in this script chunk separately, one of them will often converge. This approach generates a `fit` model object while running the whole chunk generates a `try_error` object *using the exact same script on the exact same data* and I have no idea why. I'm hoping one of you will see some obvious mistake in the script causing this behavior. Thanks! 

```

    # this script includes progressive checks for model fitting issues, and re-runs fit_model with different specifications as necessary.  
    # WC is separated because of the extra catchability coefficient for their survey change 
    
    # attempt 0: estimate parameters without estimating standard errors, just so we have them if needed later. this should run fine for all species. 
    if(reg %in% c('ebs','neus')){
      fit0 =try(
        fit_model("settings"=settings, "Lat_i"=Data_Geostat[,'Lat'],
                  "Lon_i"=Data_Geostat[,'Lon'], "t_i"=Data_Geostat[,'Year'],
                  "c_i"=rep(0,nrow(Data_Geostat)), "b_i"=Data_Geostat[,'Catch_KG'],
                  "a_i"=Data_Geostat[,'AreaSwept_km2'], 
                  "getReportCovariance"=FALSE, "getJointPrecision"=TRUE,
                  lower=-Inf, upper=Inf,
                  test_fit = FALSE,
                  fine_scale=fine_scale,
                  anisotropy=FALSE,
                  Use_REML=TRUE,
                  Z_gm = Z_gm,
                  getsd=FALSE,
                  newtonsteps=0
        ))
      
      # attempt 1: re-run model with SE estimation. if this model has no convergence issues as tested below, it will be the last model we run for this species. 
      fit = try(
        fit_model("settings"=settings, "Lat_i"=Data_Geostat[,'Lat'],
                  "Lon_i"=Data_Geostat[,'Lon'], "t_i"=Data_Geostat[,'Year'],
                  "c_i"=rep(0,nrow(Data_Geostat)), "b_i"=Data_Geostat[,'Catch_KG'],
                  "a_i"=Data_Geostat[,'AreaSwept_km2'], 
                  "getReportCovariance"=FALSE, "getJointPrecision"=TRUE,
                  lower=-Inf, upper=Inf,
                  test_fit = FALSE,
                  fine_scale=fine_scale,
                  anisotropy=FALSE,
                  Use_REML=TRUE,
                  Z_gm = Z_gm,
                  getsd=TRUE,
                  newtonsteps=1
        ))
                                                                                                           fit$parameter_estimates$adjustments_for_convergence <- "none"
      
      
      # check that all maximum gradients have an absolute value below 0.01 and the model didn't throw an error 
      if(class(fit)=="try-error" || (!class(fit)=="try-error" &  max(abs(fit$parameter_estimates$diagnostics$final_gradient)) > 0.01)){
        
        # attempt 2: if fit didn't work above, try re-running it with the parameter estimates from fit0
        fit = try(
          fit_model("settings"=settings, "Lat_i"=Data_Geostat[,'Lat'],
                    "Lon_i"=Data_Geostat[,'Lon'], "t_i"=Data_Geostat[,'Year'],
                    "c_i"=rep(0,nrow(Data_Geostat)), "b_i"=Data_Geostat[,'Catch_KG'],
                    "a_i"=Data_Geostat[,'AreaSwept_km2'], 
                    "getReportCovariance"=FALSE, "getJointPrecision"=TRUE,
                    lower=-Inf, upper=Inf,
                    test_fit = FALSE,
                    fine_scale=fine_scale,
                    anisotropy=FALSE,
                    Use_REML=TRUE,
                    Z_gm = Z_gm,
                    getsd=TRUE,
                    newtonsteps=1,
                    parameters=fit0$ParHat
          ))
        fit$parameter_estimates$adjustments_for_convergence <- "used fit0 parameters"
        
        }
      
      
      # check that all maximum gradients have an absolute value below 0.01 and the model didn't throw an error 
      
      if(class(fit)=="try-error" || (!class(fit)=="try-error" &  max(abs(fit$parameter_estimates$diagnostics$final_gradient)) > 0.01)){
        
        # attempt 3: if fit still failed / didn't converge, it could be because L_beta1_cf or L_beta2_ct is approaching zero; use a different RhoConfig 
        
        # if it's a model, but didn't converge... 
        if(!class(fit)=="try-error"){
          if(abs(fit$parameter_estimates$par["L_beta1_cf"]) < 0.001) {
          newRhoConfig = c("Beta1"=3, "Beta2"=4, "Epsilon1"=4, "Epsilon2"=4)
        }
        if(abs(fit$parameter_estimates$par["L_beta2_ct"]) < 0.001) {
          newRhoConfig = c("Beta1"=4, "Beta2"=3, "Epsilon1"=4, "Epsilon2"=4)
        }
        if(abs(fit$parameter_estimates$par["L_beta1_cf"]) < 0.001 & 
           abs(fit$parameter_estimates$par["L_beta2_ct"]) < 0.001) {
          newRhoConfig = c("Beta1"=3, "Beta2"=3, "Epsilon1"=4, "Epsilon2"=4)
        }}
        
        # if it's an error...
        if(class(fit)=="try-error"){
          newRhoConfig = c("Beta1"=3, "Beta2"=3, "Epsilon1"=4, "Epsilon2"=4)
        }
        
        fit = try(
          fit_model("settings"=settings, 
                    "RhoConfig"= newRhoConfig,
                    "Lat_i"=Data_Geostat[,'Lat'],
                    "Lon_i"=Data_Geostat[,'Lon'], "t_i"=Data_Geostat[,'Year'],
                    "c_i"=rep(0,nrow(Data_Geostat)), "b_i"=Data_Geostat[,'Catch_KG'],
                    "a_i"=Data_Geostat[,'AreaSwept_km2'], 
                    "getReportCovariance"=FALSE, "getJointPrecision"=TRUE,
                    lower=-Inf, upper=Inf,
                    test_fit = FALSE,
                    fine_scale=fine_scale,
                    anisotropy=FALSE,
                    Use_REML=TRUE,
                    Z_gm = Z_gm,
                    getsd=TRUE,
                    newtonsteps=1,
                    parameters=fit0$ParHat
                    
          ))
        fit$parameter_estimates$adjustments_for_convergence <- "changed RhoConfig"
      }
    }    
```

**Comment by Cole-Monnahan-NOAA** [comment]
This error

````
Error in par[-random] <- x : replacement has length zero
````
I've only seen when the Laplace approximation in TMB fails and so it returns a NaN in the inner loop and that triggers this error in the outer loop. 

But, everything you're doing should be deterministic: the initial values, determining the mesh, the inner and outer loops, etc. So I don't see anything immediate that should cause this behavior. Here's a couple thoughts:

Does it behave like this when you run in serial but as a script rather than manually? Or only in parallel? 

When you run manually, do you get exactly the same fit if you rerun the same code chunk that succeeds a few times? 

Does it always return that error above, or something else sometimes? I would use unique fit names, fit0, fit1, fit2, etc. That way when the clause is finished running you can check what happened at each step. 

When you change the Rho settings, are you sure you're not changing the parameter structure in the model? If you are then you can't pass the parameter estimates from a previous fit. E.g, if your parameters are c(x1,x2,x3) in one fit, then c(x1,x3) in the next b/c you dropped a parameter, then if you pass the MLE of c(x1,x2,x3) it will have the wrong structure.

**Comment by afredston** [comment]
Thanks! To answer your questions:

1. Yes, this behavior happens when I run in serial but as a script
2. I haven't checked if the parameter estimates are the exact same if I re-run the same chunk multiple times, but I haven't noticed different species having totally different results among model runs. I can try this today but it'll take awhile. 
3. That error is definitely the most common but I think in the past it's also returned just `Error in par[-random] <- x : replacement has length zero` or just `Error in `*tmp*`$parameter_estimates : 
  $ operator is invalid for atomic vectors`. Great idea re: model names, I will fix that now. 
4. It's very possible I fed it the wrong model structure, and maybe that's the source of some of the issues (although I still don't know why running the `fit_model()` calls separately would fix it). Would you remove the `parameters=fit0$ParHat` from what I'm now calling `fit3`, where we change `RhoConfig`?

**Comment by Cole-Monnahan-NOAA** [comment]
(1) I'm not aware of any reason why `try` would be different when sourcing it vs running it interactively. So that's very weird. Are you clearing your workspace of the fit objects between species/regions? 
(2) that's concerning! Are you using some new or uncommon feature of VAST?
(3) I think this will tell you a lot once it's done running. 
(4) Passing fit0$ParHat makes sense  only when the model is unchanged (like going from fit0 to fit), so yes anytime you change it let VAST initialize by removing that.

**Comment by afredston** [comment]
An update on this issue:

* Removing the erroneous `parameters=fit0$ParHat` fixed numerous convergence issues in the final attempt to run `fit_model`
* I figured out why the script wasn't working as a whole, which was a very stupid mistake, and also causing the `$ operator is invalid for atomic vectors` error. If the model resulted in a `try-error`, the line creating `fit$parameter_estimates$adjustments_for_convergence` (a new list I was adding for reference) threw an error. Wrapping it in `if(!class(fit)=="try-error) {}"` fixed the issue. 

Huge thanks for the help @Cole-Monnahan-NOAA!
