### ISSUE TITLE
delta strategy + problem with VAST installation

### ISSUE THREAD

**Issue by slefores** [James-Thorson-NOAA/VAST#247]
Hi,
I am working on a case study on which I am only focusing on positive CPUE values and I would like to know if the DELTA strategy is optional or not with VAST ? 

Otherwise, I tried in two ways to install VAST but I always got an error (it seems to be the installation of FishStatsUtils which fails in both cases) :

1.	With the ‘classic’ way :
`devtools::install_github("james-thorson/VAST", INSTALL_opts="--no-staged-install")`

```
Error: package or namespace load failed for 'VAST':
 .onAttach failed in attachNamespace() for 'VAST', details:
  call: NULL
  error: Failed to install 'FishStatsUtils' from GitHub:
  (converti depuis l'avis) cannot remove prior installation of package 'backports'
Erreur : le chargement a échoué
Exécution arrêtée
*** arch - x64
Error: package or namespace load failed for 'VAST':
 .onAttach failed in attachNamespace() for 'VAST', details:
  call: NULL
  error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
```
2.	With the way proposed on issue #179 :
```
install.packages("TMB")
install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
devtools::install_github("james-thorson/FishStatsUtils", ref="2.2.0")
devtools::install_github("james-thorson/VAST")
```
```
Downloading GitHub repo james-thorson/FishStatsUtils@2.2.0
James-Thorson-NOAA-FishStatsUtils-a7518f0/data/bc_coast_grid.rda: truncated gzip input
tar.exe: Error exit delayed from previous errors.
Error: Failed to install 'FishStatsUtils' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\sl\AppData\Local\Temp\RtmpM5iPOI\file558c7a217f01.tar.gz" -C "C:/Users/sl/AppData/Local/Temp/RtmpM5iPOI/remotes558c25897f5c"’ returned error code 1
2: In system(cmd, intern = TRUE)
```
Thank you!

**Comment by ChristineStawitz-NOAA** [comment]
1.  Release 2.2.0 of `FishStatsUtils` looks quite old and potentially not ideal for the current version of `VAST` you are using. If you try again without the `ref` argument, does it install?

2. I was having a slightly different install problem, but on the advice of @Cole-Monnahan-NOAA I was able to fix it by running `update.packages()` in R first, then installing `FishStatsUtils` from Github, then installing VAST using `devtools::install_github("james-thorson-NOAA/VAST", dependencies = FALSE)`. Does that work?

**Comment by slefores** [comment]
Thank you for your answer Christine, it works !

```
install.packages("TMB")
install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
install.packages(“backports”)
devtools::install_github("james-thorson/FishStatsUtils")
devtools::install_github("james-thorson/VAST",dependencies=FALSE)
```

**Comment by ChristineStawitz-NOAA** [comment]
Great no problem! I don't seem to be able to, but it sounds like we can close this issue.
