### ISSUE TITLE
make_data error with covariates

### ISSUE THREAD

**Issue by TiffanyVidal** [James-Thorson-NOAA/VAST#251]
Hello,
I just updated my R (4.0.2) and VAST versions (v9_4_0) and ran into an error when running code that has run successfully with an older version (MWE below). It looks as though there may be an issue with the make_data function in the newest version (line  233)
```r
X_ip = array( X_itp[,1,], dim=X_itp[c(1,3)] )
```
I think that perhaps it should include a `dim` function around X_itp[c(1,3)]?
```r
X_ip = array( X_itp[,1,], dim=dim(X_itp[c(1,3)]) )
```
As is, it seems to be using data values as the dimensions, and throwing an error because the dimension is negative.
**Error in array(X_itp[, 1, ], dim = X_itp[c(1, 3)]) : the dims contain negative values**

```r
# Load packages
library(VAST)
library(tidyverse)

# load data set
example = load_example( data_set="covariate_example" )
samp.dat = as.data.frame(example$sampling_data) 

t_i = match(samp.dat[,'Year'],   unique(samp.dat[,'Year']))

# Make settings (turning off bias.correct to save time for example)
settings = make_settings( n_x=10,
                          Region=example$Region,
                          purpose="index2",
                          use_anisotropy=FALSE,
                          bias.correct=FALSE,
                          fine_scale=TRUE )

# Random covariate with negative values
cov_data = samp.dat %>%  mutate(Year = t_i, FAKE_COV = runif(nrow(samp.dat),-2,0)) %>% select(Lat,Lon,Year,FAKE_COV)

# Define formula 
formula = ~FAKE_COV

# Density covariate  - spatially varying
Xconfig_zcp = array( 2, dim=c(2,1,1) )

# Run model
fit = fit_model( settings = settings,
                 FieldConfig=rep(0,4),
                 ObsModel_ez = c(1,0), 
                 Lat_i = samp.dat[,'Lat'],
                 Lon_i = samp.dat[,'Lon'],
                 t_i = t_i,
                 b_i = samp.dat[,'Catch_KG'],
                 a_i = samp.dat[,'AreaSwept_km2'],
                 formula = formula,
                 covariate_data = cov_data,
                 Xconfig_zcp = Xconfig_zcp)
```
Thanks in advance for any thoughts/suggestions on this issue.

**Comment by James-Thorson-NOAA** [comment]
I've just pushed hotfix release number 3.5.4.  The formula interface for covariates is being expanded in the development branch, so I will also make the fix there (if the problem is present).  Could you please check this release and close the issue if you confirm that its fixed?

**Comment by TiffanyVidal** [comment]
Thanks, Jim. I just reran with your update and appears I had a mistake in the suggested fix. I believe it should be:
```
X_ip = array( X_itp[,1,], dim=dim(X_itp)[c(1,3)] )
```
I had the second parentheses in the wrong place. Apologies for that. This seems to be working.

**Comment by James-Thorson-NOAA** [comment]
OK, I made that change in a new branch 'hotfix'.  Could you please test there and close the issue if it now passes your explorations?

**Comment by TiffanyVidal** [comment]
Working great. Thanks again!
