### ISSUE TITLE
Interpreting covariate parameter estimates

### ISSUE THREAD

**Issue by mkajanus** [James-Thorson-NOAA/VAST#253]
Hi,

I have difficulties extracting species-specific parameter estimates for covariates. I have ran a multivariate delta-model for continuous data of 25 species, with two covariates.

In the parameter estimates I get 50 estimates for gamma1_ctp, which is the "effect of density covariates that change over time on encounter prob", and 50 estimates for gamma2_ctp ("effect of density covariates that change over time on positive catch rates"). I would need to extract species-specific parameter estimates from these. Hence, within each 50 parameter estimates, in what order are the results presented?

Are the first 25 estimates in gamma1_ctp and gamma2_ctp the effects of covariate 1 for each species and the next 25 the effects of covariate 2 for each species? Or, are the parameter estimates presented so that first two estimates are for species number one for covariates 1 and 2, the next two estimates are for species number two for covariates 1 and 2 etc.?

Also, in what order are the species listed in the parameter estimates?

What would be the most reliable method for extracting the correct species-specific effects of the covariates?

Thank you for your time.
Best,
Mira

**Comment by James-Thorson-NOAA** [comment]
you can run `as.list( fit$parameteter_estimates$SD, what="Estimate")` to get the estimates in matrix form.  The rows are ordered according to `c_i` value (or its numeric value when supplied as a factor) supplied when running the model.

happy to keep discussing but closing for now.
