### ISSUE TITLE
Estimating catchability covariates with no temporal overlap

### ISSUE THREAD

**Issue by ACharsley** [James-Thorson-NOAA/VAST#256]
Hi,

I'm attempting to build a model which incorporates presence/absence data of freshwater eels from two different survey types. These survey types are historical data (obtained from records of customary fishing grounds dating back to over 100 years ago) and electrofishing data (sampled in recent years).

Ideally, I would like to include a catchability covariate to account for differences in expected catch rates between the survey types. Or perhaps a vessel effect. However, the effect is only estimable when there is overlap between the surveys. Do you have any advice on what the best way is to go about this modelling work? One option I considered was to date the historical data to the earliest electrofishing data. This is not ideal but allows for temporal overlap whilst enabling historical data to better inform the trend.   

Thanks!

**Comment by James-Thorson-NOAA** [comment]
I don't think there's any statistical fix for resolving a gear-power difference when you have paired co-located samples and also don't have any samples that are sufficiently close in space and time to have some correlation (arising from the specified form and estimated values for those forms of correlation).  I guess you could just specify different potential values and explore it as a sensitivity, or develop a prior based on theoretical considerations and similar species.

**Comment by ACharsley** [comment]
Thanks Jim! So this would require specifying potential values for lambda1_k? How can these be set?

I understand how to switch off lambda1_k using:
```
Map = fit$tmb_list$Map
Map$lambda1_k = factor(NA)
```
But can they be fixed in a similar way?

**Comment by James-Thorson** [comment]
yeah, just do the same thing -- extract an initial version of
`fit$tmb_list$Parameters`, modify the starting value for `lambda1_k`, and
then feed it back into `fit_model` when its mapped off.
