### ISSUE TITLE
inconsistent terminology for RhoConfig values of 4 between make_data and user manual

### ISSUE THREAD

**Issue by afredston** [James-Thorson-NOAA/VAST#257]
The VAST user manual (lines 299-300) says:

2. Autoregressive - `RhoConfig[3]=4` and `RhoConfig[4]=4` specifies epsilon1 and epsilon2 as a fixed effect

But in `make_data()` the documentation for `RhoConfig` says that `4: each year as random following AR1 process`. 

I always thought this setting specified a random effect, not a fixed effect--just wanted to flag this as an area to clarify between the different pieces of documentation.

**Comment by James-Thorson-NOAA** [comment]
I'm a little confused -- the master and development branch User Manuals line 296-300 both state:
```
where ρ_ε1 and ρ_ε2 are the estimated degree of first-order autocorrelation in temporal variation, RhoConfig[3] controls the specification of ρ_ε1:
	Random walk  – RhoConfig[3]=2 specifies ρ_ε1=1
	Autoregressive – RhoConfig[3]=4 estimates ρ_ε1 as a fixed effect
and settings are defined identically for RhoConfig[4] specifying ρ_ε2. 
```

So the text is clarifying that the rho parameter is a fixed effect when using an AR1 process (which is true).  can you clarify your concern?  

I'm closing the issue for now but happy to keep discussing improvements in the description, or revising as needed.

**Comment by afredston** [comment]
OK, sounds like I misunderstood! Anyway, my read of the documentation for `make_data()` is still that the rho parameter would be a **random** effect when using an AR1 process. Would it be (more?) accurate to say `4: each year as fixed following AR1 process` or rephrase to match wording in the user manual?

**Comment by James-Thorson-NOAA** [comment]
Thanks for pointing out these ambiguities!  I am just now revising the `make_data()` reference documentation to be more clear about what is a random of fixed effect in each instance (the epsilon/beta terms are typically random effects, and variance/correlation terms are typically fixed effects)

**Comment by afredston** [comment]
I see, that makes a ton of sense. Thanks for clarifying :)
