### ISSUE TITLE
PDO as a covariate

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#262]
Hi,
How do I specify a covariate with a unique annual value in the model? I am using an annual Pacific Decadal Oscillation index (mean of August and Sept PDO). In my .csv file I repeat the unique PDO value for each observation in a year. I normalized the PDO (PODn).

**Here is my code:** 

X1_formula=~PDOn
X2_formula=~PDOn
X1<-data.frame(Lat,Lon, Year, PDOn)

settings = make_settings( Version="VAST_v12_0_0",
                          n_x=50,
				  Region="Other",
                          strata.limits=strata.limits,
                          purpose="index2",
				  bias.correct=TRUE,
                         # max_cells = Inf,
                          max_cells=2000,
                          ObsModel=c(1,3),
				  fine_scale=TRUE,
				  FieldConfig=c(1,1,1,1),
                         treat_nonencounter_as_zero=TRUE)
settings$grid_size_km = 60

fit = fit_model(
			"settings"=settings,
                 "Lat_i"=temp[,'Lat'],
                 "Lon_i"=temp[,'Lon'],
                 "observations_LL" = temp[,c('Lat','Lon')],
		     "t_i"=temp[,'year'],
		     #"c_i"=as.numeric(temp[,'Sci'])-1, 
		     "c_iz"=rep(0,nrow(temp)), # for single species 
                 "b_i"=temp[,'Wt'],
                 "a_i"=temp[,'AreaSwept'],
                # "getsd"=TRUE,
                 "getsd"=FALSE,
                 "test_fit"=TRUE,
                 "maximum_distance_from_sample" = 75,
                 "build_model" = TRUE,
                 "X1_formula"=X1_formula, 
                 "X2_formula"=X2_formula, 
                 "vars_to_correct"="Index_cyl",
                 "covariate_data"=X1
)
~~~~~~~~~~~~~~~

Here are the last few model iterations and my error message:
 52:     1352.4578: 0.799654 0.332486 0.332832 -0.140777 0.0153734  1.99360 -1.49588 -1.74322 0.281174 -0.435307 -0.795815 -0.916295 0.419894 -1.05616  3.10196  1.09388  1.02524  1.20488  1.30505 -4.10751  1.83958  1.90186  1.52471  2.59232  1.81575  1.61924  1.72405 0.538115  2.00742  2.14832  1.72445  2.64415  2.62403  3.33293 0.487331 -1.42000 -1.10674 -3.81270 0.296159
 53:     1352.4578: 0.799813 0.332577 0.332520 -0.140557 0.0153824  1.99293 -1.49560 -1.74336 0.280592 -0.435929 -0.796169 -0.916319 0.420032 -1.05616  3.10213  1.09370  1.02530  1.20485  1.30498 -4.10741  1.83952  1.90206  1.52468  2.59230  1.81596  1.61936  1.72407 0.537952  2.00779  2.14843  1.72422  2.64436  2.62414  3.33295 0.487338 -1.42011 -1.10676 -3.81277 0.296150
 54:     1352.4578: 0.799815 0.332563 0.332641 -0.140495 0.0152986  1.99311 -1.49547 -1.74320 0.280464 -0.435725 -0.796034 -0.916179 0.420041 -1.05620  3.10228  1.09380  1.02531  1.20484  1.30501 -4.10737  1.83951  1.90203  1.52468  2.59228  1.81586  1.61933  1.72405 0.537949  2.00776  2.14838  1.72432  2.64437  2.62419  3.33304 0.487352 -1.42009 -1.10675 -3.81278 0.296155
 55:     1352.4578: 0.799847 0.332580 0.332730 -0.140607 0.0154045  1.99322 -1.49552 -1.74321 0.280488 -0.435687 -0.795946 -0.916161 0.420028 -1.05619  3.10223  1.09383  1.02529  1.20487  1.30505 -4.10734  1.83951  1.90199  1.52469  2.59228  1.81588  1.61931  1.72399 0.537960  2.00769  2.14836  1.72438  2.64435  2.62416  3.33306 0.487357 -1.42009 -1.10677 -3.81275 0.296152
  0:     1352.4578: 0.799847 0.332580 0.332730 -0.140607 0.0154045  1.99322 -1.49552 -1.74321 0.280488 -0.435687 -0.795946 -0.916161 0.420028 -1.05619  3.10223  1.09383  1.02529  1.20487  1.30505 -4.10734  1.83951  1.90199  1.52469  2.59228  1.81588  1.61931  1.72399 0.537960  2.00769  2.14836  1.72438  2.64435  2.62416  3.33306 0.487357 -1.42009 -1.10677 -3.81275 0.296152
  1:     1352.4578: 0.799847 0.332579 0.332729 -0.140605 0.0154030  1.99322 -1.49552 -1.74321 0.280489 -0.435687 -0.795948 -0.916161 0.420028 -1.05619  3.10223  1.09383  1.02529  1.20487  1.30505 -4.10734  1.83951  1.90199  1.52469  2.59228  1.81588  1.61931  1.72399 0.537960  2.00769  2.14836  1.72438  2.64435  2.62416  3.33306 0.487356 -1.42009 -1.10677 -3.81275 0.296158
  2:     1352.4578: 0.799848 0.332578 0.332729 -0.140603 0.0154011  1.99322 -1.49552 -1.74321 0.280489 -0.435687 -0.795949 -0.916162 0.420029 -1.05619  3.10223  1.09383  1.02530  1.20487  1.30505 -4.10734  1.83951  1.90199  1.52469  2.59228  1.81588  1.61931  1.72399 0.537961  2.00769  2.14836  1.72437  2.64434  2.62416  3.33306 0.487354 -1.42009 -1.10677 -3.81275 0.296153
  0:     1352.4578: 0.799848 0.332578 0.332729 -0.140603 0.0154011  1.99322 -1.49552 -1.74321 0.280489 -0.435687 -0.795949 -0.916162 0.420029 -1.05619  3.10223  1.09383  1.02530  1.20487  1.30505 -4.10734  1.83951  1.90199  1.52469  2.59228  1.81588  1.61931  1.72399 0.537961  2.00769  2.14836  1.72437  2.64434  2.62416  3.33306 0.487354 -1.42009 -1.10677 -3.81275 0.296153
  1:     1352.4578: 0.799848 0.332578 0.332729 -0.140603 0.0154011  1.99322 -1.49552 -1.74321 0.280489 -0.435687 -0.795949 -0.916162 0.420029 -1.05619  3.10223  1.09383  1.02530  1.20487  1.30505 -4.10734  1.83951  1.90199  1.52469  2.59228  1.81588  1.61931  1.72399 0.537961  2.00769  2.14836  1.72437  2.64434  2.62416  3.33306 0.487354 -1.42009 -1.10677 -3.81275 0.296153
**Error in solve.default(h, g) : 
  system is computationally singular: reciprocal condition number = 3.43616e-19**
> check = Check_Identifiable( fit$tmb_list$Obj )
**Error in if (any(Gr > 0.01)) stop("Some gradients are high, please improve optimization and only then use `Check_Identifiable`") : 
  missing value where TRUE/FALSE needed**

Any suggestions are appreciated. Thank you
Ellen

**Comment by James-Thorson-NOAA** [comment]
Thanks for asking in a searchable way!

Please consider running same with a small edit `fit_model( ..., newtonsteps=0)`.  This should then avoid the singular-Hessian issue that arises during estimation.

However, looking at the code I can guess that the issue is that you haven't edited the default `X1config_cp` and `X2config_cp` settings as needed for this application.  Please also edit as:

```R
fit_model( ..., 
  X1config_cp = array(2,dim=c(1,1)),
  X2config_cp = array(2,dim=c(1,1))
)
```

The point is that the default setting is assuming a linear effect of cold-pool-extent and this is then confounded with the default specification of intercepts.  Instead, you want to use a zero-centered spatially varying effect, and the code is listed in `?make_data` following justification here: https://www.sciencedirect.com/science/article/abs/pii/S0079661119304240

**Comment by EllenY** [comment]
Thank you for the assistance and reference ; )
https://rdrr.io/github/James-Thorson/FishStatsUtils/man/fit_model.html

**Comment by James-Thorson-NOAA** [comment]
Before I forget ... the FishStatsUtils development branch (release 2.9.0) includes automated plots for the spatially-varying slope term for density covariates like you're exploring here.  That obtained using `plot( fit, ..., plot_set = c(18,19))`.  I haven't tested it much though, so I guess you'd be the guinea pig ;0
