### ISSUE TITLE
Acronyms for model output and estimates of SE

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#263]
Hi 
I am looking for: 
1. Definitions of the acronyms for the model output given in summary(fit$Report)
2. Standard errors for mean estimates of effective area occupied (fit$Report$effective_area_ctl),  northing and eastings (fit$Report$mean_Z_ctm), and biomass (fit$Report$Index_ctl)

fit = fit_model( "settings"=settings,
                 "Lat_i"=temp[,'Lat'],
                 "Lon_i"=temp[,'Lon'],
                 "observations_LL" = temp[,c('Lat','Lon')],
                 "t_i"=temp[,'year'], #model without covariates
                 "b_i"=temp[,'Wt'],
                 "a_i"=temp[,'AreaSwept'],
                 "getsd"=TRUE,
                 "test_fit"=TRUE,
                 "maximum_distance_from_sample" = 75,
                 "build_model" = TRUE
)

summary(fit$Report)
                   Length Class  Mode   
Xi1_gcp                0  -none- numeric
Xi1_scp                0  -none- numeric
Omega1_sc            104  -none- numeric
beta2_tc              17  -none- numeric
Omega2_gc           2000  -none- numeric
B1_cc                  1  -none- numeric
D_gct              34000  -none- numeric
Epsilon1_gct       34000  -none- numeric
Epsiloninput1_sft   1768  -none- numeric
R1_gct             34000  -none- numeric
a_average              1  -none- numeric
Ltime_epsilon1_tf    289  -none- numeric
L_beta2_cf             1  -none- numeric
L_omega1_cf            1  -none- numeric
Omegainput2_sf       104  -none- numeric
L_epsilon2_cf          1  -none- numeric
P1_iz                809  -none- numeric
diag_iz             3236  -none- numeric
sigmaPhi2_k            0  -none- numeric
jnll                   1  -none- numeric
Index_ctl             17  -none- numeric
SigmaM                 3  -none- numeric
Xi2_gcp                0  -none- numeric
sigmaXi2_cp            0  -none- numeric
Xi2_scp                0  -none- numeric
jnll_comp             18  -none- numeric
Omega1_gc           2000  -none- numeric
eta1_vc                1  -none- numeric
B2_cc                  1  -none- numeric
Epsiloninput2_sft   1768  -none- numeric
R2_gct             34000  -none- numeric
Epsilon2_sct        1768  -none- numeric
eta1_gct           34000  -none- numeric
P1_gct             34000  -none- numeric
Ltime_epsilon2_tf    289  -none- numeric
Omegainput1_sf       104  -none- numeric
L_epsilon1_cf          1  -none- numeric
L_omega2_cf            1  -none- numeric
H                      4  -none- numeric
D_i                  809  -none- numeric
R1_i                 809  -none- numeric
P2_iz                809  -none- numeric
pred_jnll              1  -none- numeric
mean_D_ctl            17  -none- numeric
sigmaXi1_cp            0  -none- numeric
Range_raw1             1  -none- numeric
Range_raw2             1  -none- numeric
Omega2_sc            104  -none- numeric
eta2_vc                1  -none- numeric
beta1_tc              17  -none- numeric
Epsilon1_sct        1768  -none- numeric
P2_gct             34000  -none- numeric
eta2_gct           34000  -none- numeric
iota_ct               17  -none- numeric
Epsilon2_gct       34000  -none- numeric
L_beta1_cf             1  -none- numeric
R2_i                 809  -none- numeric
sigmaPhi1_k            0  -none- numeric
effective_area_ctl    17  -none- numeric
Index_gctl         34000  -none- numeric
mean_Z_ctm            34  -none- numeric

Thank you

**Comment by James-Thorson-NOAA** [comment]
I recommend skipping the definition of all slots in `fit$Report` for now.  Instead, please note that all ploting-functions in VAST invisibly return all numbers needed to reproduce those plots, e.g.,

```R
fit = fit_model( ... )
plot_output = plot(fit)
summary(plot_output)
```

Those slots are named semi-intuitively, and I recommend looking through the contents and matching numeric values against those in the plots to confirm your that you're looking at the right values.  And of course I'm happy to iterate on this thread if you have follow-up questions.  I'll leave this open until you close it (or several months go by without use, whichever comes first)

**Comment by EllenY** [comment]
How do I extract the standard errors of the estimates? 
In the fit$Report, I see the estimates but not the standard errors for the effective area occupied estimates (fit$Report$effective_area_ctl), northing and eastings estimates (fit$Report$mean_Z_ctm), and biomass estimates (fit$Report$Index_ctl).

**Comment by EllenY** [comment]
Here it is!
x=summary(fit$parameter_estimates$SD, select='report')
