### ISSUE TITLE
Potential typos in make_map.R

### ISSUE THREAD

**Issue by agruss2** [James-Thorson-NOAA/VAST#264]
Hi, I think that I spotted some typos in make_map.R (master branch):

(1) Line 222: 
```R
Map[["L2_z"]] = factor(rep(NA,length(TmbParams[["L1_z"]])))
```
which should be replaced with:
```R
Map[["L2_z"]] = factor(rep(NA,length(TmbParams[["L2_z"]])))
```

(2) Line 290: 
```R
Map[["gamma2_j"]] = factor(Map[["gamma1_j"]])
```
which should be replaced with:
```R
Map[["gamma2_j"]] = factor(Map[["gamma2_j"]])
```

(3) Line 476: 
```R
if(DataList$X1config_cp[cI,pI] %in% c(0,1)) Map[["Xiinput2_scp"]][,cI,pI] = NA
```
which should be replaced with:
```R
if(DataList$X2config_cp[cI,pI] %in% c(0,1)) Map[["Xiinput2_scp"]][,cI,pI] = NA
```

Many thanks!

**Comment by James-Thorson-NOAA** [comment]
Thanks Arnaud!  This is very helpful and I appreciate you giving this a careful read.  I am making a hotfix branch for these which I will push as a bug-fix release semantic number 3.6.1 today. 

Regarding these bugs:
1. I don't think L1_z and L2_z ever have different length in practice
2. corresponds to an old backwards compatibility feature
3. occurs when spatially varying density effects are different between linear predictors

Anyway, none of these would arise often, so I suspect that they have not caused user issues, but I still greatly appreciate your help in identifying and fixing them.  Please point along similar issues at any time!
