### ISSUE TITLE
Implementing p-splines in VAST

### ISSUE THREAD

**Issue by agruss2** [James-Thorson-NOAA/VAST#271]
Currently, it is possible to implement polynomials, natural splines and B-splines in VAST thanks to the use of "formula". 
It would also be great to implement p-splines in VAST, as p-splines usually do a better job at modeling the non-linear effects of environmental conditions that are poorly sampled (e.g., the effects of very high bottom temperatures on fish density). 
Therefore, I was wondering if p-splines could make it to the "Development priorities"? https://github.com/James-Thorson-NOAA/VAST/wiki/Development-priorities 
My understanding is that the implementation of p-splines would necessitate some additional code in the CPP files and that Nicholas Ducharme-Barth has already some ideas on this issue.  
Many thanks!

**Comment by James-Thorson-NOAA** [comment]
Agreed :) just added to [dev priorities](https://github.com/James-Thorson-NOAA/VAST/wiki/Development-priorities)
