### ISSUE TITLE
Density plot error for years with 0% encounters

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#274]
Hi

The density plots show high densities in years (2004 and 2012) with 0% encounter for Aequorea jellyfish. Is there a way to modify code to get the correct results to plot?

![ln_density-predicted](https://user-images.githubusercontent.com/7538663/105619132-109df200-5d9c-11eb-9e3c-8e1f4f43372d.png)

settings = make_settings( Version="VAST_v12_0_0",
                          n_x=30,
			 Region="Other",
                          strata.limits=strata.limits,
                          purpose="index2",
			 bias.correct=TRUE,
                          max_cells = 2000,
                          ObsModel=c(1,3),
			 use_anisotropy=TRUE,
  			 fine_scale=TRUE,
			 FieldConfig=c(1,0,1,0),	
                         treat_nonencounter_as_zero=TRUE)
settings$grid_size_km = 40

fit = fit_model( "settings"=settings,
                 "Lat_i"=temp[,'Lat'],
                 "Lon_i"=temp[,'Lon'],
                 "observations_LL" = temp[,c('Lat','Lon')],
                 "t_i"=temp[,'year'], 
                 "b_i"=temp[,'Wt'], 
                 "a_i"=temp[,'AreaSwept'],
                 "getsd"=TRUE,
                 "test_fit"=TRUE,
                 "maximum_distance_from_sample" = 42,
                 "build_model" = TRUE
)

plot_results(fit=fit, settings=settings, plot_set=c(3), cex.main=3, cex=2)

Thank you
Ellen

**Comment by James-Thorson-NOAA** [comment]
Ellen,

Thanks for asking on the issue tracker.  I can see how the existing docs are not clear. Simple answer -- `plot_results` has an argument `years_to_plot` that you can specify to control what years are plotted throughout the plots.  Could you please try that?

I will also improve docs on the development branch.  The problem arises because I changed naming convention for `fit_model` relative to internal logical functions, and that meant that `fit_model` wasn't auto-labeling the relevant input.  I will fix this by changing to use the same naming conventions as `fit_model` for those internal functions.

I'm closing the issue for now but feel free to report progress on this thread.

**Comment by EllenY** [comment]
Many thanks! I’ll give it a try

**Comment by EllenY** [comment]
I want to plot specific years 2002:2012, 2014, 2016, 2018. 

fit$year_labels = c( 2002, fit$year_labels )
fit$years_to_plot = c(1, fit$year_labels+1)

plot_results(
  fit,
  settings = fit$settings,
  plot_set = 3,
  working_dir = paste0(getwd(), "/"),
  year_labels = fit$year_labels,
  years_to_plot = fit$years_to_plot,
  use_biascorr = TRUE,
 # map_list,
  #category_names,
  check_residuals = TRUE,
  projargs = "+proj=longlat",
 # zrange,
  n_samples = 100,
  calculate_relative_to_average = FALSE,
  type = 1,
  n_cells = NULL,
 # RotationMethod = "PCA",
  quantiles = c(0.05, 0.5, 0.95)
)

ERROR:

### Making plot of abundance index
Error in (function (TmbData, Sdreport, year_labels = NULL, years_to_plot = NULL,  : 
  `year_labels` must have same length as `TmbData$n_t`

**Comment by James-Thorson-NOAA** [comment]
Ellen -- Thanks for asking here on the issue tracker.  Cole has just made a demo that is now on the [Wiki here](https://github.com/James-Thorson-NOAA/VAST/wiki/Plots-using-ggplot), showing how to plot variables using ggplot.  Of course the default code is also available for `plot_variable`.    

@Cole-Monnahan-NOAA -- thanks for putting together the example!
