### ISSUE TITLE
Seasonal VAST ex

### ISSUE THREAD

**Issue by brianstock-NOAA** [James-Thorson-NOAA/VAST#289]
I had a couple issues running the [seasonal VAST model example](https://github.com/James-Thorson-NOAA/VAST/wiki/Seasonal-model). I'm not too familiar with VAST (that's why I'm running the example) so apologies if there are searchable solutions...

1. At the `fit_orig` step, I get these warnings:
```
Warning messages:
1: In sparseMatrix(i = index.i, j = index.j, x = Aij, dims = c(mesh$n,  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
2: In sparseMatrix(i = index.i, j = index.j, x = Aij, dims = c(mesh$n,  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
3: In sparseMatrix(i = index.i, j = index.j, x = Aij, dims = c(mesh$n,  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
```

2. The estimate parameters step eventually errors out, no `fit` saved.
```
Error in optimHess(parameter_estimates$par, fn = fn, gr = gr) : 
  gradient in optim evaluated to length 1 not 85
In addition: There were 38 warnings (use warnings() to see them)
```

`warnings()` shows the above 3, then
```
4: In (function (TmbData, Version, RhoConfig = c(Beta1 = 0,  ... :
  Please carefully check starting values for all parameters to ensure that mapping off parameters will work as expected.
```
and the rest are
```
5: In nlminb(start = startpar, objective = fn, gradient = gr,  ... :
  NA/NaN function evaluation
```

3. How long does it take to run on your computer? It took 48+ hours on mine. Maybe add a warning it takes that long? I started it in the evening with the hope it'd be done in the morning!

4. In the comments it says the development branch is required. This initially stumped me because I installed the development branch of VAST and the `NWA_yellowtail_seasons` dataset wasn't available. Would be good to clarify that the development branch of `FishStatsUtils` is required, not just (or in addition to?) the VAST development branch.

If useful, I can send the intermediate files. My `sessionInfo` is
```
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 19.1

other attached packages:
[1] FishStatsUtils_2.9.0 VAST_3.7.0           TMB_1.7.19
```

**Comment by abesolberg** [comment]
I had a similar issue, and I think it's tied to your version of Matrix (see issue #287 ). Try reinstalling Matrix version 1.2.8 using devtools. That did the trick for me. 

`devtools::install_version("Matrix", version = "1.2.8")`

**Comment by aallyn** [comment]
Hi Brian, definitely agree on the Matrix piece for resolving the warnings and errors. For the speed, are you on a Mac? If so, you might have a look into changing the BLAS library used. [Here are some instructions](https://mpopov.com/blog/2019/06/04/faster-matrix-math-in-r-on-macos/). After making those modifications, I’m able to run the example in around 45 minutes to an hour.

**Comment by brianstock-NOAA** [comment]
Thank you, I appreciate the speedy replies! Sorry, this was a general install issue and not related to the seasonal example... I'll rename this thread. I should have made sure the simple ex worked before jumping to the seasonal.

After following your instructions at #280 to downgrade Matrix to 1.2.8 and TMB to 1.7.18, I am now able to run the simple (16 min), seasonal (2.1 hrs), and length comp (47 min) examples. There were a few install hiccups along the way - initially following #280 did not work. Apologies to anyone who reads this in the future, but I do not recall the steps or in what order.

I first tried reinstalling TMB with [this recent fix](https://github.com/kaskr/adcomp/issues/340), without downgrading Matrix. I think that resolved the `optimHess` error but not the `sparseMatrix` warnings... can't remember.

I got an install error with SpatialDeltaGLMM that I think was caused by the DESCRIPTION [line 48](https://github.com/nwfsc-assess/geostatistical_delta-GLMM/blob/master/DESCRIPTION#L48) needing to be updated to point to the new INLA URL. The current link is broken: https://www.math.ntnu.no/inla/R/stable. Should be https://inla.r-inla-download.org/R/stable? I got some confusing error messages about INLA not being installable even though I had the latest INLA installed separately beforehand. Error was resolved by making sure all SpatialDeltaGLMM dependencies were updated/installed in advance, in my case `mapdata`.

Thanks for the help, I can play with VAST now. Hopefully the Matrix/TMB issue will get resolved because my main job is developing [WHAM](https://github.com/timjmiller/wham) and we specify to use the latest GitHub version of TMB.

--------------------

Thanks for the BLAS thought, but 2.1 hour runtime is reasonable enough that I don't want to worry about it. I'm curious - how long do the simple and length comp examples take on your machine? I'm on Linux using openblas:
```
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 19.1

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
```
It seems like openblas did fine in these comparisons:
https://csantill.github.io/RPerformanceWBLAS/
https://brettklamer.com/diversions/statistical/faster-blas-in-r/#faster-blas-in-r-for-ubuntu
https://www.r-bloggers.com/2013/07/for-faster-r-use-openblas-instead-better-than-atlas-trivial-to-switch-to-on-ubuntu/

**Comment by James-Thorson-NOAA** [comment]
How many threads do you have?  I have 16 threads on my laptop, which are parallelized using MRAN.  Using BLAS, I'm assuming that the time will scale as the reciprocal of number of threads ...?

**Comment by brianstock-NOAA** [comment]
Maybe that's it. I'm using Intel Core i7-8650U CPU @ 1.90GHz × 4 = 8 threads, with 32gb RAM.

In any case, some guess for what the run times should be for the examples would be nice. Could also make the examples smaller to allow people to more quickly 1) confirm VAST is working and 2) play with the fit model objects. The examples look great but could probably only use ~1/3 the years. Could keep the full/existing examples, just separately as simple_full, seasonal_full, etc.

I know there are only so many hours in the day... Just an idea - take it or leave it!
