### ISSUE TITLE
DHARMa residual plots

### ISSUE THREAD

**Issue by jin-gao** [James-Thorson-NOAA/VAST#294]
Hi Jim, 

I've been playing around with the DHARMA residuals and I find most of the times the K-S test, dispersion test and outlier test significant. The outliers seem to be the big tows. What alternative model structure would be appropriate? I used Tweedie distribution with different Rhoconfig settings. I also got similar deviations with different ObsModel. 

Another question I find is that the multispecies residuals vs. predicted plot (right one in the standard DHARMa plots) look strange and I cannot seem to have it plot it by species. 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/15019774/111523053-cdc61e00-873d-11eb-8f11-046e21327a8e.png)

Did I plot the residuals right?...

Thanks,

Jin

**Comment by James-Thorson-NOAA** [comment]
I don't trust the p-values from DHARMa;  they're not accounting for random effect variances.  

DHARMa some some interface for showing residuals by category or whatever, and the object is outputted, but you'll have to do some digging.  Or the old functions for diagnostics are still available in FishStatsUtils, but you'll have to set them up yourself.

**Comment by James-Thorson-NOAA** [comment]
Following up ... you might look at `recalculate_residuals` in [DHARMa docs](https://cran.r-project.org/web/packages/DHARMa/DHARMa.pdf)

**Comment by jin-gao** [comment]
Great! And also the PIT residuals maybe useful.
