### ISSUE TITLE
Plotting functions do not produce all figures

### ISSUE THREAD

**Issue by mkajanus** [James-Thorson-NOAA/VAST#295]
Hello,

I am trying to use the different plotting functions (actually from FishStatsUtils), but the functions are not producing all the plots or the maps are not correctly displayed. The analyses were run with R version 3.6.2 and VAST release 3.4.0. For the plotting, I am now using R version 4.0.3, VAST release 3.7.1 and FishStatsUtils version 2.9.1.

1. "Plot_results"-function with the "fit"-object produces maps for the "plot_set" argument and "quantile_residuals_on_map"-figures. However, these maps only show heat map colors (in the maps for the estimated values of "plot_set") over the sea area, whereas the land area (Finland) is grey without any estimates displayed (see the first figure below). Although I know that the extrapolation of estimates in not possible at an unspecified area, such as Finland, in a previous version of VAST (release 2.0.1) we have been able to produce maps with points of "plot_set" estimates (e.g. covariate or predicted density; see the second figure below) and the residual maps were also correctly displayed (see the third figure below). Is this still possible? Here is my code:

plot_results(fit, plot_set = 3, category_names = levels(Data_Geostat[, "c_iz"]))

The only warnings I receive are:

In wkt(obj) : CRS object has no comment
In spTransform(xSP, CRSobj, ...) :
  NULL source CRS comment, falling back to PROJ string

2. Plotting the factors on a map from my "fit"-object with "plot_factors"-function, produces the factor loadings figures (bar charts) correctly. However, it does not produce any maps to show the factor loadings. I don't receive any error messages or warnings from the function either and it runs normally. Here is my code:

plot_factors(fit = fit, Report = fit$Report, ParHat = fit$ParHat, Data = fit$data_list,
             SD = fit$parameter_estimates$SD, mapdetails_list = MapDetails_List, Year_Set = Year_Set,
             category_names = levels(Data_Geostat[, "c_iz"]),
             plotdir = paste0(DateFile, "/Factors"))

3. "summarize_covariance"-function does not produce any of the covariance matrix figures, although the matrices were "normally" produced in the last version of VAST that we used (release 3.4.0). This function now only produces the covariances in R (saved as "Cov_List" in the example below). My code is:

Cov_List <- summarize_covariance(Report = fit$Report, 
					   Data = fit$data_list, 
					   ParHat = fit$ParHat,
                                 SD = fit$parameter_estimates$SD, 
					   plot_cor = FALSE, 
					   figname = NULL, 
					   category_names = levels(Data_Geostat[, 'c_iz']),
                                 plotdir = DateFile, 
				   	   plotTF = NULL, 
					   mgp = c(2, 0.5, 0), tck = -0.02, oma = c(0, 5, 2, 0))
 

![ln_density--ALAARV-predicted](https://user-images.githubusercontent.com/41282655/111817939-49170380-88e7-11eb-922a-755c159a02e5.png)

![NewMod_FinalDens](https://user-images.githubusercontent.com/41282655/111817764-1836ce80-88e7-11eb-8145-0f032b6f8429.png)

![maps--catchrate_pearson_resid](https://user-images.githubusercontent.com/41282655/111822918-035d3980-88ed-11eb-8254-dbc2fd870c24.png)

I can send you reproducible examples if required. Thank you for your help in advance.

Sincerely,
Mira

**Comment by James-Thorson** [comment]
Please see '?plot_variable' I believe there's an argument land_color that
can be changed for transparent land

**Comment by mkajanus** [comment]
Thank you for your quick response. I used "land_color=rgb(0,0,0,alpha=0.1)" argument and this allowed the point estimates to be visible. However, the resulting figure leaves the right side column of maps white, while the other maps are transparent with grey color (see figure below). Would you know how to fix this?

Additionally, the issues with the other functions still remain:

First, "plot_factors"- function does not provide any maps with the factor loadings? Furthermore, for my colleague this function has worked, providing maps of factor loadings, and he has tried using the "land_color=rgb(0,0,0,alpha=0.1)"  argument as it is listed as one of the arguments, but it does not have any effect within this function (and the resulting maps look like mine above with only grey land area). We have not found out the reason, why this is not working. It would be very useful to have the option for land area transparency within the arguments of "plot_results"- and "plot_factors" -functions, so the user would not need to find and extract the correct estimates from the "fit"-object and use "plot_variables"-function (although this works as well).

Second, the "summarize_covariance"-function does not provide any figures (or warnings or errors for that matter either)?

Thank you again for your time.
Best,
Mira

![density](https://user-images.githubusercontent.com/41282655/111864857-1a8f3c00-896c-11eb-8bf2-9f36cc1f3e58.png)

**Comment by James-Thorson-NOAA** [comment]
Yeah, I'm confused about both of those issues:
* `land_color` should pass through `plot_factors` based on the code
* I can't imagine why the right-hand column has different behavior.  

I can't commit to maintaining the plots as carefully as the actual logical code, so I'm sorry but I think you'll need to muddle through with extracting the output and making your own plots.  I'd welcome any specific code suggestions on this thread, which I would integrate in the dev branch.  but I'm closing for now.
