### ISSUE TITLE
Catcability covariates for seasonal model 

### ISSUE THREAD

**Issue by SostheneA** [James-Thorson-NOAA/VAST#299]
Hi Dr. Jim,
I estimated a VAST seasonal model without catcability and covariates effects.

The reviewer Ask me to add the flag (factor variable with 2 modalities) and carring capacity (factor variable with 8 modalities) as catcability variables in the model .

I try to do it with the simplified interface developped by Andrew to implement seasonal spatio-temporal models, but i do not Know how to add these two catcabilities variables in the model.

My catcability_data have these parameters : Lon, Lat, year, Season, Year_season , Flag and carring_capacities .

My Sampling data have these parameters : Lon , Lat , weight, swept, Areakm2 ,year, Season and Year_season.

Can you help me to specify the catcability data ans others parameters likes Q_ik or Q1_formula in the fit_model function ?

**Comment by James-Thorson-NOAA** [comment]
Thanks for your interest in exploring and sounds like an interesting study :)

The seasonal model includes additional terms as "habitat covariates".  The catchability terms you've mentioned are "catchability covariates".  Thus, you use a different interface for each.

I don't have a demo for catchability covariates on the Wiki, but please see again [here](https://github.com/James-Thorson-NOAA/VAST/wiki/Specify-covariates-and-visualize-responses) for the formula interface, and instead specifying catchability covariates using arguments `catchability_data`, `Q1_formula` and `Q2_formula`.  I'd be happy to discuss identifiability here if you provide more details about the factors being discussed.

Please close the issue if this is sufficient info

**Comment by SostheneA** [comment]
The fishing segment that I analyze concerns French and Spanish purse seiners that use vessels of different sizes (carrying capacities). Both are categorical variables.
The purpose of adding these two variables is to test if they have an impact on the estimated abundance index. 
If I understand correctly, I just have to specify them as such?
Q1_formula = ~flag,
 Q2_formula = ~Capacity,
 covariate_data = dataframe(flag=data$flag, Capacity=data$Capacity)

There would be no other specifications to make like Andrew example [:](https://github.com/James-Thorson-NOAA/VAST/wiki/Seasonal-model)

# Implement corner constraint for linear effect but not spatially varying effect:
# * one level for each term is 2 (just spatially varying)
# * all other levels for each term is 3 (spatialy varying plus linear effect)
X1config_cp_use = matrix( c(2, rep(3,nlevels(cov_dat$Season)-1), 2, rep(3,nlevels(cov_dat$Year_Cov)-1) ), nrow=1 )
X2config_cp_use = matrix( c(2, rep(3,nlevels(cov_dat$Season)-1), 2, rep(3,nlevels(cov_dat$Year_Cov)-1) ), nrow=1 )

And

# Adjust mapping for log_sigmaXi and fitting final model -- pool variance for all seasons and then set year's to NA
Map_adjust = fit_orig$tmb_list$Map

# Pool variances for each term to a single value
Map_adjust$log_sigmaXi1_cp = factor(c(rep(as.numeric(Map_adjust$log_sigmaXi1_cp[1]), nlevels(cov_dat$Season)),
  rep(as.numeric(Map_adjust$log_sigmaXi1_cp[nlevels(cov_dat$Season)+1]), nlevels(cov_dat$Year_Cov))))
Map_adjust$log_sigmaXi2_cp = factor(c(rep(as.numeric(Map_adjust$log_sigmaXi2_cp[1]), nlevels(cov_dat$Season)),
  rep(as.numeric(Map_adjust$log_sigmaXi2_cp[nlevels(cov_dat$Season)+1]), nlevels(cov_dat$Year_Cov))))

**Comment by James-Thorson-NOAA** [comment]
correct, no mapping needed I don't think; I think it should be smart enough to implement a corner constraint automatically.

**Comment by SostheneA** [comment]
OK Thank James.
