### ISSUE TITLE
Interpreting effective area occupied results

### ISSUE THREAD

**Issue by ACharsley** [James-Thorson-NOAA/VAST#305]
Hi,

I'm running single-category species distribution models in VAST for freshwater fish in a stream network. We use a binomial model and 'switch off' the 2nd model component. I wanted to know if the calculation of effective area occupied still made sense and could be interpreted? The plot seems to reflect changes in encounter probability over time very well. The effective area occupied calculation relies on density and indices which don't really make when the 2nd model component is 'switched off'. 

Thanks,
Anthony

**Comment by James-Thorson-NOAA** [comment]
Yes, the effective-area-occupied (EAO) will involve an arbitrarily specified unit in the calculation of the index (i.e., the scale of `b_i` associated with an encounter) and the same unit in the calculation of density, and then EAO is calculated as their ratio such that this arbitrary scale unit cancels out.  Obviously there's the same disclaimer as for other derived quantities in this analysis, that the user must specify some tiny "jitter" in presences to estimate `SigmaM` and this results in an arbitrarily small noise in the calculation.  

I'm closing for now but feel free to follow up on this thread.

**Comment by ACharsley** [comment]
Thanks Jim!
