### ISSUE TITLE
as_units function ?

### ISSUE THREAD

**Issue by jimianelli** [James-Thorson-NOAA/VAST#306]
in https://github.com/James-Thorson-NOAA/VAST/wiki/Unbalanced-data seems to be missing and couldn't find in fishutils and other places (nor in ThorsonUtilities).

**Comment by James-Thorson-NOAA** [comment]
thanks for catching that.  its now used in the development branch with backwards compatibility, and it fixes the wrong-units issues in previous plots and output.  in the meantime, I just removed it from the wiki example you flagged.
