### ISSUE TITLE
Overlapping circles in the plots

### ISSUE THREAD

**Issue by Mahdi2022** [James-Thorson-NOAA/VAST#308]
Hi, I have 277 points and run the VAST model with Mesh method and 277 knots, but I got some overlapping circles in the plots (Figures 1,2) which do not make sense. I checked the coordinates and all of them are different (Figure 3). I also ran the model with less knots(100) with Mesh and Grid methods, I still got the same figures.

![Figure 3](https://user-images.githubusercontent.com/43444574/123801834-50d94180-d8f3-11eb-9154-8cf46896b96b.jpg)
![Figure 2](https://user-images.githubusercontent.com/43444574/123801837-520a6e80-d8f3-11eb-8940-ba51f3fcb776.PNG)
![Figure 1](https://user-images.githubusercontent.com/43444574/123801840-52a30500-d8f3-11eb-8d69-15975d8c231b.PNG)

**Comment by James-Thorson-NOAA** [comment]
I'll see if anyone else has insight.  but I'm guessing:

1. you're using an old version of VAST, which now plots maps using raster variables by default
2. perhaps you're inferring the location of grid cells from the location of samples, which then results in some grid cells being right next to each other ... it is better practice to explicitly define the extrapolation domain e.g. using a shapefile or custom built grid

closing for now but happy to keep chatting
