### ISSUE TITLE
plot error/unable to extract sd into a dataframe for mapping in ggplot 

### ISSUE THREAD

**Issue by caitlinkroeger** [James-Thorson-NOAA/VAST#309]
I am encountering an error while trying to use the code below to map standard errors for modeled seabird densities. I am running EOF3 models (option "SD_site_logdensity"= TRUE) using VAST 3.7.1. 

```
> out<-plot(Model2_cv, plot_set=3,  plot_value = sd)

### Running `plot_results`

### Creating plots in directory /home/jovyan/CWS Project/

### Making plots of data availability and knots
NULL source CRS comment, falling back to PROJ stringCRS object has no commentError in aperm.default(Psi_gjt, c(1, 3, 2)) : 
  invalid first argument, must be an array
```

Although nothing saves at 'out', maps are generated that are labeled as “transformed” - are these the sd maps? Is the label transformed because the sd values are logged? I suspect this error is also why residual plots are not generated? They were when I used VAST.  Or is there different code I should be using?

Thank you in advance and please let me know if there is additional information I should provide.

**Comment by James-Thorson-NOAA** [comment]
I'm really sorry to be so slow in responding.  option `"SD_site_logdensity"= TRUE` is basically deprecated, and the preferred way to get SDs is using the `plot_value` input to `plot_maps`.  did you ever resolve this on your side?  

I'm closing for now, but happy to iterate here if you have questions
