### ISSUE TITLE
Compilation failed simpleError in TMB::compile

### ISSUE THREAD

**Issue by gfmg** [James-Thorson-NOAA/VAST#312]
Hi there, 

I am a recently new VAST user. I have been using VAST for approx. over a month, and until now I have been able to implement models and run VAST without any problem (including examples on wiki). 

However, today, when running some examples, I am facing the following compilation error: 

`Compilation failed<simpleError in TMB::compile(paste0(Version, ".cpp"), flags = "-Wno-ignored-attributes -O2 -mfpmath=sse -msse2 -mstackrealign"): Compilation failed>`

I have not changed anything on my code, or updated neither VAST or TMB. Not sure what the issue is exactly. 

Thanks you very much for any help.

**Comment by James-Thorson-NOAA** [comment]
I've never seen this before, but happy to bat ideas around.

1. What is your OS?
2. what shows up in R terminal given command `packageVersion("VAST")`?
3. have you tried restarting your computer to retry?
4. have you tried re-installing the same numeric release for VAST and retrying?

Obviously I don't have any specific ideas ... it seems like a TMB issue but happy to investigate before making that conclusion.

**Comment by gfmg** [comment]
Hi Jim, 

Thanks for your fast reply. Answering your ideas above: 

1- Windows
2- ‘3.7.1’
3- Yes, I have. Issue persist. 
4- I have just removed TMB and VAST from R and re-install them. Retried fitting the models, but the issue persist. 

Not sure if helpful, but the laptop I am currently using is not personal, but belongs to my institution. Following this thread: https://github.com/kaskr/adcomp/issues/277, some users suggested to change the `~/.R/Makevars` file. Although I don't know if both issues are related (I don't think so), I am not allowed to modify this file as I dont have administration permission. I am wondering if this could be related? In any case, it is strange that I was able to run VAST before.

Sorry I cannot provide much further information or insights

**Comment by James-Thorson-NOAA** [comment]
Yeah, I wonder if Rtools (and associated CPP compilers) were somehow deleted ... I've had this happen for other dependencies in some institutional machines (like the `INLA` object `fmesher.exe`).  

What about trying to re-install the R software and associated Rtools?

**Comment by gfmg** [comment]
Thanks Jim, 

Will contact the IT section, in case any support occurred in our machines thisthe morning that could have affected the files you mention. Otherwise I will re-install R and R-tools and get back to you in the issue

**Comment by gfmg** [comment]
Hi again, 

My IT department has guaranteed that they do not interact with any R files. 

However, re-installing R and Rtools (and re-specifying the R-Environ) solved the issue. I really don't know what has caused this change in behavior. 

I will close the comment. Thanks so much for your help again. 

Guille

**Comment by afredston** [comment]
hey @gfmg, we recently started a Slack group for VAST users. feel free to send me an email if you want to join (fredston@rutgers.edu), and of course it's fine if you don't!
