### ISSUE TITLE
How combine presence/absence, counts, and biomass data work?

### ISSUE THREAD

**Issue by AlbanAkia** [James-Thorson-NOAA/VAST#317]
Hi everyone,
I planed to use the joint models fitting encounter, count, and biomass-sampling data (Grüss and Thorson, 2019).

I tried to understand how results are obtained, but I did not quite understand how count data (in num) and biomass data (in kg) are put together to end up with an abundance index in kg.

Is the final result equal to encounter*count*biomass (express in kg), or are the counts transformed in biomass to ensure a result in kg in the model [encounter*(count transform in kg+biomass)?

Thanks.

**Comment by James-Thorson-NOAA** [comment]
Thanks for your interest in this feature!  Adding @agruss2 given that he is also an expert on the topic.  

In short version:

1. Fitting biomass using a Poisson-linked delta model involves two linear predictors, representing log-numbers density and weight-per-number, and involves some distribution for weight given the product of the two
2. Fitting counts then only uses the 1st of those linear predictors, and assumes some counting process given that predictor
3. Fitting presence/absence then uses the 1st linear predictor, based on the probability that the counting process from (2) would result in a zero or nonzero count.  

I'd be happy to get into details here or feel free to email me directly if you wanna work through a minimal example.  and I assume you've already seen the Wiki example [here](https://github.com/James-Thorson-NOAA/VAST/wiki/Combine-biomass-counts-and-encounter-data)

**Comment by AlbanAkia** [comment]
Thanks @James-Thorson-NOAA 

Let me presente my study case.

I planned to analyse purse seine catch data.
For this gear, we do not considered the specie one by one as longline but the fish school. 
So we want to estimate a 3 components model on VAST by using the number of fish school catch on a day as count data (Poisson) . Then considered the biomass per fish-school as Biomass data and a third composent wich is the proportion of the target specie in a catched fish-school (binomial).

I hope that the result will be count*biomass*proportion 

So, i want to Know if it make sense to think that the combine model work like that.

is the result abundance index estimated in VAST represente this kind of analysis or results ?

**Comment by James-Thorson-NOAA** [comment]
This is a super-interesting use-case.  Unfortunately, the "combined data" is defined for a case where you have some measurement of total biomass, some separate measurement for the count, and/or some separate measurement of presence-absence.  By contrast, I think you're describing a slightly different case where you have a measurement of count, a measurement of biomass-per-count, and then a separate measurement of a proportion (which I don't really follow but probably doesn't matter for now).  

Using VAST for this, I think it would best be done using multivariate VAST model, using `c=0` for the numerical density, `c=1` for the biomass-per-count or school or whatever, and `c=2` for the proportion, using `Expansion_cz` to generate an index that takes the product of all three variables when calculating the index.  `ObsModel_ez` could then be used to specify a zero-inflated lognormal-Poisson for counts, a gamma for biomass, and something else TBD for the proportion.  However, I don't have any guidance really for doing this online.   

Feel free to respond here or email ... I'm guessing you'd want to connect with another expert in VAST to get the model set up given how non-standard it would be

**Comment by AlbanAkia** [comment]
Thanks @James-Thorson-NOAA ,
This is a good news.
I will response by email for the model set up , so i will close this issue if you are agree with that.
