### ISSUE TITLE
How to use the Seasonal model to obtain the abundance values of an uninvestigated season (spring) in a year in the survey sequence of multiple seasons (spring, summer and autumn)?

### ISSUE THREAD

**Issue by Hanqingpeng** [James-Thorson-NOAA/VAST#325]
How to use the Seasonal model to obtain the abundance values of an uninvestigated season (spring) in a year in the survey sequence of multiple seasons (spring, summer and autumn)?
As Thorson et al., 2020, Index of relative Abundance of Yellowtail flounder in 1985/1986 was obtained by using Seasonal model .
I tried the code from the wiki for the Seasonal model and applied it to my data, but did not get the predicted value for the unsurveyed year-season.   Instead, I get a zero abundance value.The following:
。。。。
2015 Stratum [kg] 0  0  0
2015.3  Stratum [kg] 52264  26015  0.7
00000

**Comment by James-Thorson-NOAA** [comment]
I'm guessing that you have `settings$Options['treat_nonencounter_as_zero'] = TRUE` ... could you confirm that in the `settings.txt` produced, and explore changing that to `FALSE` prior to re-running the model?

**Comment by Hanqingpeng** [comment]
Perfect. Thank you very much. After modifying the Settings, The model has reached the result I want.

In addition, ALTHOUGH I set RhoConfig = c("Beta1" = 3, "Beta2" = 3, "Epsilon1" = 4, "Epsilon2" = 4) in settings$, I received a Warning message.  If there is no problem with this, I am comfortable applying the results.
Warning message:
In (function (TmbData, Version, RhoConfig = c(Beta1 = 0, Beta2 = 0,  :
  Please carefully check starting values for all parameters to ensure that mapping off parameters will work as expected.
>

**Comment by James-Thorson-NOAA** [comment]
The seasonal model requires customizing the `map` by hand.  However, doing so can cause some unintended issues, hence the warning.  If you're following the seasonal-model wiki and all of the output looks reasonable, then I suspect you're fine.  But feel free to email me if you wanna discuss your case in detail.
