### ISSUE TITLE
Spatially-varying catchability models

### ISSUE THREAD

**Issue by agruss2** [James-Thorson-NOAA/VAST#326]
Hi, 
I am currently working on a case study involving two different datasets and am using spatially-varying catchability models. I am using the Poisson-link delta distribution model. It appeared relevant to me to estimate spatially-varying catchability for both the first and the second linear predictors. 
My question is: Are there some specific cases where it would be relevant not to estimate spatially-varying catchability for the first or the second linear predictor? 
Many thanks!

**Comment by James-Thorson-NOAA** [comment]
Using the Poisson-linked delta model for ecological data, I typically assume the effect size will be larger for random effects (i.e., larger standard deviation, or larger change in AIC when comparing with removing the effect) for the 1st than the 2nd linear predictor.  But yes, you can test spatially varying catchability with either/both predictors, and use AIC or other evidence to select a reduced model.

**Comment by agruss2** [comment]
Thanks a lot, Jim, this is interesting and I'll follow your recommendations :)
