### ISSUE TITLE
Field and Rho Configuration guides

### ISSUE THREAD

**Issue by CacciapagliaC** [James-Thorson-NOAA/VAST#327]
I'm going through model iterations trying to optimize which configurations to use and I've been trying to find a concise guide to interpreting Field and Rho configurations and understand how they have changed between versions of VAST. For instance FieldConfig = c(Omega1 = "IID", Epsilon1 = "IID", Omega2 = "IID", Epsilon2 = "IID") and (1,1,1,1) result in the same parameters being estimated but vary slightly in their estimation and I haven't been able to find any literature on why or how to interpret the differences.

I have found some useful flow charts with the numeric configurations and their interpretation, but can't find a comprehensive guide. Is there a suggested location to find more?

**Comment by James-Thorson-NOAA** [comment]
Hmm.  Is this a univariate or multivariate model?  I'm definitely curious to learn more ... I would think that `FieldConfig = c(Omega1 = "IID", Epsilon1 = "IID", Omega2 = "IID", Epsilon2 = "IID")` and `FieldConfig = c(1,1,1,1)` would give the same results in a univariate model.

Regarding your question ... I assume you've already read the Details section of `?make_data` ...?  Can you clarify what information is missing, and perhaps I can use your suggestions to improve docs so others can benefit too?

**Comment by CacciapagliaC** [comment]
These are univariate models. It was my impression that they should be the same as well, which is why I was wondering what was going on behind the scenes, and if I misinterpreted how fieldConfig was being assigned.  

Here's my current understanding, please correct me if I'm mistaken. 
The old FieldConfig framework was just turn on (1) or off (0) spatial and spatiotemporal components, when switching to the new framework the on (1) has become "IID".  Now there are other options like AR1, and Identity, and integer greater than 0 (I'm assuming that this is somehow ignored when input is 1 and there are no covariates, since 1 is also an integer greater than 0). Most of these new options are for multivariate models, and I haven't gone into depth with how to interpret them. Which along with my confusion on why the 1111 and IID's were providing different estimates led me to my question if there was a compiled list or table of input and interpretations somewhere. 

Something more like:
(1,1,1,1) = spatial and spatiotemporal components turned on, each year has spatial predicitons, use for estimating localized biomass through years
FieldConfig IID,IID,0,0 = ignore spatial correlation within years i.e. all years are homogenous - use for estimating overall biomass through years
[c("Omega","Epsilon"),"Component_1"] = "IID" = (1,1,0,0) 
1,0,1,1= spatial and temporal correlation only correlated among years - used for?
Or these very helpful ones from your publication. 
This decision is again made by specifying the input `FieldConfig` where e.g., `FieldConfig = c("Omega1"=4, "Epsilon1"=3, "Omega2"=0, "Epsilon2"=0)` indicates that VAST should use four factors for spatial variation in the 1st linear predictor, three factors for spatio-temporal variation in the 1st linear predictor, and turn off spatial and spatio-temporal variation in the 2nd linear predictor (this input would only make sense when analyzing data for four or more categories).

I understand that this information is possible to tease apart from the make_settings with a good understanding of model structure, and help files are probably best left compact. I have found some interpretations like these scattered throughout publications and examples in various versions, but I was wondering if you knew of any comprehensive sources where the model configurations were more flushed out to help interpret the structure, which I imagine only gets more complicated moving into the multivariate structure.  


 
As for the differences between (1,1,1,1) and (IID IID IID IID) I have attached the parameter files and put the settings at the bottom for a couple sets of runs, everything should be identical between the runs except changing between IID and 1's in the FieldConfig. You are welcome to give it a look. Let me know if you would like anything else to help out.

with Rho 1,1,0,0
[parameter_estimates IID Rho1100.txt](https://github.com/James-Thorson-NOAA/VAST/files/8612241/parameter_estimates.IID.Rho1100.txt)
[parameter_estimates 1111 rho1100.txt](https://github.com/James-Thorson-NOAA/VAST/files/8612265/parameter_estimates.1111.rho1100.txt)

and with Rho 2,2,0,0
[parameter_estimates 1111 Rho 2200.txt](https://github.com/James-Thorson-NOAA/VAST/files/8612376/parameter_estimates.1111.Rho.2200.txt)
[parameter_estimates IID Rho2200.txt](https://github.com/James-Thorson-NOAA/VAST/files/8612377/parameter_estimates.IID.Rho2200.txt)

**Comment by James-Thorson-NOAA** [comment]
Thanks for sharing these!  If I'm reading this right, the MLE values are nearly identical (difference < 0.001) and the ML objective function is also nearly identical (difference < 0.01, below print-out rounding).  However, you should be able to get them identical to nearly machine tolerance.   

Am I right that you're using `fit_model( ..., newtonsteps=0)`?  If yes, could you try `fit_model( ..., newtonsteps=1)` and confirm that the change gets them even closer?

I might be missing something, but it seems like these are functionally identical as expected ... please tell me if you wanna return to the original question about decision guidance or something.

**Comment by CacciapagliaC** [comment]
Ah interesting, thank you. Yes I have newtonsteps at 0, I can set it to 1 and see what happens. Would setting a seed for this component make it exactly identical? I noticed that they were extremely similar, but if IID and 1 were the same I was expecting it to be identical when using the same data, and it surprised me that there were some differences. It looked like I had introduced stochasticity and I couldn't figure out what in the model would be responsible.  

As for guidance on decisions, do you know of a resource explaining in more detail the various configurations? 
I'm seeing which univariate model configuration are best scoring for three different species, and going through relevant model types I have 3 obsmodel configs (2,4,9), 2 links (0,1), 4 Rho Configurations(0000,1100,2200,3300,4400), and potentially 2 Field Configurations (1111,1011). This ends up being a lot of iterations, and I'm trying to see if I am missing anything relevant or can cut out anything.  Thank you!

**Comment by James-Thorson-NOAA** [comment]
Yeah, I generally suggest doing some "model decisions" based on a priori needs, rather than model selection per se.  Feel free to email me if that's easier.  For index standardization, for example, assessment software and reviewers typically expect indices that are independent among years, so that requires `settings$RhoConfig[c("Beta1","Beta2)] = 0` in most cases.  

I'll close for now, but please do post observations about `newtonsteps=1`
