### ISSUE TITLE
Suggestion: add option for calculating index as sum across categories

### ISSUE THREAD

**Issue by N-DucharmeBarth-NOAA** [James-Thorson-NOAA/VAST#331]
Hi Jim,
I'm just adding this issue based on the conversation that we had today. It would be useful to have the option to calculate the index as the sum across categories. This could be applied in cases where an index is needed at the complex level but observations are attributed to individual species using the category (`c_iz`) object. You had mentioned that this could be accomplished through a modification to `Expansion_cz`.
Best,
Nicholas

**Comment by James-Thorson-NOAA** [comment]
Thanks for the suggestion!

I just added to the dev branch a new option where e.g. you could calculate the sum across three area-weighted categories by specifying:

```R
Expansion_cz = cbind( c(0,3,3), c(0,0,1) )
```
where `Report$Index_ctl[3,,1]` would then be the sum of area-weighted response across all categories. I tried adding doxygen docs a bit but if this is useful would welcome ideas for how to better unobtrustively document this.

I'll close for now.  But are you willing to try updating to dev, test this and do a quick sniff test, and then respond here with any impressions?

**Comment by N-DucharmeBarth-NOAA** [comment]
Hi Jim,
Sorry for the delay, was finally able to get around to testing this feature today.

Applying ```Expansion_cz = cbind( c(0,3,3), c(0,0,1) )``` to an existing 3 category model I can confirm that ```Report$Index_ctl[3,,1]``` gives the sum across the 3 categories when compared to a model where ```Expansion_cz = cbind( c(0,0,0), c(0,0,0) )```. Additionally,  ```Report$Index_ctl[2,,1]``` gives the sum across the first two categories. This looks like it will get me what I'm looking for.

The only downside to this implementation is that in order to pull out the individual trends for categories 2 & 3, the model has to be re-run with ```Expansion_cz = cbind( c(0,0,0), c(0,0,0) )```. Not a big issue though.

**Comment by James-Thorson-NOAA** [comment]
Great!  Glad it's working.  And yes, I thought originally about making `Expansion_cz` more generic but decided it wasn't worth the extra difficulty documenting and explaining, given that it's possible to reload the model passing `Parameters = fit$Obj$env$parList()` etc.
