### ISSUE TITLE
issue with custom maps code example

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#332]
Hi
In running the example Wiki code for custom maps in ggplot located here: https://github.com/James-Thorson-NOAA/VAST/wiki/Plots-using-ggplot I have the following error. I am using VAST_14_0_1. How do I remedy this? 
g <- gmap +
+   geom_point(data=D, aes(Lon, Lat, color=log(D), group=NULL),
+              ## These settings are necessary to avoid
+              ## overlplotting which is a problem here. May need
+              ## to be tweaked further.
+              size=.3, stroke=0,shape=16) + facet_wrap('Year')
> g
Error in Ops.units(x, range[1]) : 
  both operands of the expression should be "units" objects

Many thanks!

**Comment by EllenY** [comment]
Same error again. strip_units does not seem to strip the units.
166 10021 2012  5413.342365 [kg/km^2] 58.97452 -175.4341       1

**Comment by James-Thorson-NOAA** [comment]
well, I'm not an expert in ggplot2 ... I'm sure it's a matter of removing the units from all objects being passed and recommend modifying all things being passed until they are unit-free.  please see `strip_units` for ideas on how to do so.

**Comment by EllenY** [comment]
Changing color=log(D) to color=log(as.vector(D)) seems to work.

g <- gmap +
  geom_point(data=D, aes(Lon, Lat, color=log(as.vector(D)), group=NULL),
             ## These settings are necessary to avoid
             ## overlplotting which is a problem here. May need
             ## to be tweaked further.
             size=.3, stroke=0,shape=16) + facet_wrap('Year')

g

**Comment by James-Thorson-NOAA** [comment]
Thanks for posting the fix!  I just updated the [wiki example](https://github.com/James-Thorson-NOAA/VAST/wiki/Plots-using-ggplot) to reflect that
