### ISSUE TITLE
Get standard errors or CV for density estimates by location

### ISSUE THREAD

**Issue by jlmorano** [James-Thorson-NOAA/VAST#333]
How do I find the object that contains standard errors for density estimates by location in the standard VAST output, or what code must be modified to generate these data? As an example, how were the data retrieved to map the supplementary CV figures in O'Leary et al. 2022? If it involves modifying the VAST cpp file, could you please include some basic instructions or references for how to go about doing that through R or terminal/command line?

**Comment by James-Thorson-NOAA** [comment]
Thanks for your interest!

There's a few ways to get SEs:

- The most accurate SEs are generated using a generalization of the delta-method, implemented in the CPP using `ADREPORT`.  Assuming you've run `fit = fit_model(...)`, then these are available via `fit$parameter_estimates$SD`, or in list form using `as.list(fit$parameter_estimates$SD)`.  However, this process is very slow, so not recommended for a map of densities.
- A convenient approximation is sampling from the joint precision matrix.  For some variables like density, you can run `out = plot( fit, plot_set=3, plot_value = sd)`, where the argument `plot_value` specifies the function applied to samples from the joint precision`, see `?plot_maps` for more details
- A lower-level version is available via `?sample_variable`, which gives access to samples from any REPORTed variable.

I'll close this here, but feel free to keep requesting clarification as needed.

**Comment by jlmorano** [comment]
Thank you, and I have a couple of follow up questions...

1. regarding SEs through the generalization of the delta-method, when I modified the CPP and then go to recompile, I'm getting `fatal error: 'TMB.hpp' file not found`. Any thoughts?

2. Looking at the `as.list(fit$parameter_estimates$SD)` object (when using the delta-method and the approximation from the joint precision matrix, the dimensions are not as I expect. I am expecting to find SE or SDs that would correspond to locations or the density estimates. What critical concept am I missing? I'm able to generate the map, but I want the raw data.

**Comment by James-Thorson-NOAA** [comment]
Re Q1:  As I said, I don't recommend editing the CPP to calculate the delta-method for each extrapolation-grid point or even each knot.  So no thoughts.

Re Q2: see `?as.list.sdreport` for additional background.  but that will only work if you edited the CPP which again I don't recommend.  The joint precision itself is accessed via `fit$parameter_estimates$SD$jointPrecision`

have you tried the other options I suggested?  The 2nd and 3rd bullets from my response area really the ones that I recommend using in practice.

**Comment by jlmorano** [comment]
I still was attempting to do the slow bit for my own ridiculous reasons, but yes, I have now tried the other options. I need to do a bit more reading to make sure I'm understanding the joint precision matrix correctly, and it may be my lack of familiarity with TMB functions and all of the objects within the VAST and TMB output, but how do I go from sampling the joint precision matrix to associating the variances with the lat/lon? Directing me to `fit$parameter_estimates$SD$jointPrecision` was huge help, but I'm not clear yet.

**Comment by James-Thorson-NOAA** [comment]
Sorry, I don't mean to stop you from trying Option-1 ... just proper warning that it's too slow for much use.  In VAST you can switch `settings$Options = c(settings$Options, "SD_site_density"=TRUE)` to ADREPORT `Index_gctl` 

> how do I go from sampling the joint precision matrix to associating the variances with the lat/lon?
There's no simple answer.  The User Manual has the set of equations to walk from parameters listed in `fit$parameter_estimates$SD$jointPrecision` to any quantity you're wanting to calculate.  Or you can follow the code in `sample_variable` to see how draws are calculated, passed to `fit$tmb_list$Obj$report()` and then compiled and summarized.  or elsewhere in code to find objects listing lat-lon for each extrapolation-grid cell.
