### ISSUE TITLE
Specifying type of units for b_i

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#335]
Hi
In the latest version of VAST, units are required. How do we add unit specs to b_i in the model?

                 "b_i"=temp[,'Num'],

**Comment by James-Thorson-NOAA** [comment]
I think you can either do:
* `b_i = temp[,'Num']` knowing that the unit labels are wrong and correcting interpretation yourself; or
* `b_i = as_units( temp[,'Num']  ,"count")`, which will have count units

could you please close the issue if that works?

**Comment by EllenY** [comment]
Yes, will do now. Thank you!
b_i = as_units( temp[,'Num'] ,"count") works in RStudio and R but not in the .Rmd file. The following error occurs.
Error in UseMethod("units<-") :  no applicable method for 'units<-' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"

I'll update this thread when we figure this out, looks like an variable type issue on import.
Cheers,

**Comment by James-Thorson-NOAA** [comment]
I assume the Rmd run is loading `dplyr` or something, so that `temp` is a tibble, maybe `as_units( temp$Num ,"count")` would work
