### ISSUE TITLE
plot(fit) projection different for ln density and quantile residuals

### ISSUE THREAD

**Issue by smormede** [James-Thorson-NOAA/VAST#336]
Hello,

There seems to be two different projections used when calling plot(fit) without providing a projargs. NZ falls on the pesky 180 degree line and below are examples of what the plots look like coming from the same call. Clearly it would be helpful if the ln of density was plotted with the same projection as the quantile residuals. 

It gets fixed if I give projargs, but then if I forget I have to rerun the entire model in a different folder or I get issue #315 

Hopefully this is a simple fix in the plotting function.

thanks

Sophie

![ln_density-predicted](https://user-images.githubusercontent.com/1577787/187299798-7ac254b2-b65d-498f-ad7e-859e440cf8a7.png)
![quantile_residuals_on_map](https://user-images.githubusercontent.com/1577787/187299810-bdcf40b1-ad36-4812-8861-31246f37961a.png)

**Comment by James-Thorson-NOAA** [comment]
I think I fixed this in the release I just did.  Sorry about the slow response!
