### ISSUE TITLE
Installation error - changes to @main format

### ISSUE THREAD

**Issue by pdolder** [James-Thorson-NOAA/VAST#338]
Hi,

Just a note to highlight that the installation instructions no longer work (or didn't for me), I suspect because you moved the repo across accounts and it used the updated @main format instead of @master.

This is the error:

remotes::install_github('james-thorson/VAST', INSTALL_OPTS="--no-staged-install")
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

It can be fixed by installing with 
remotes::install_github('james-thorson/VAST@main', INSTALL_OPTS="--no-staged-install"), or
remotes::install_github('James-Thorson-NOAA@main, INSTALL_OPTS="--no-staged-install")

Instructions just need updating.

**Comment by James-Thorson-NOAA** [comment]
Thanks for flagging this!  I can't replicate the issue on my machine using R 4.2.1 and remotes 2.4.2, but also don't see any issue with adding `@main` to each install call.  So I just made that edit ... does this fix things?

closing for now.

**Comment by pdolder** [comment]
Yes, that fixes it. I can see my remotes is 2.1.1 on the latest MRAN release (4.0.2) so that may be why.

**Comment by James-Thorson-NOAA** [comment]
Yeah, it's frustrating that MRAN is not updating much since changes in ownership :0

The dev-branch now has a speedup for epsilon bias-correction using framework="TMBad" which is 2-10 times faster.  So I've been using that instead of MRAN for some projects.

**Comment by pdolder** [comment]
Thanks, that's good to know, I may just switch to that. Running into several compatibility issues with MRAN.
