### ISSUE TITLE
`project_model` references undefined object `fit`

### ISSUE THREAD

**Issue by mcgoodman** [James-Thorson-NOAA/VAST#341]
In `project_model`, the argument for the fitted model object is `x`, but on line 133 (c832e9d) the function references `fit` instead of `x`:

```
a_i = c( x$data_list$a_i, as_units(rep(mean(x$data_frame$a_i),2*n_proj), units(fit$data_list$a_i)) )
```

This causes the following error when `fit` is not defined in the global environment:
> Error in UseMethod("units") : no applicable method for 'units' applied to an object of class "NULL"

**Comment by James-Thorson-NOAA** [comment]
good catch thanks!   Now fixed on dev branch.  Closing for now, but happy to maintain thread, and thanks for reporting it
