### ISSUE TITLE
Converting Eastings/Northings to Lat and Lon

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#342]
Hi  Jim,
I'm trying to convert the Eastings and Northings back to Longitude and Latitude in R. Seem to be converting E/N values back to Lon/Lat that are farther to the east than our survey. 

require(sp)
utmcoor<-SpatialPoints(cbind(Easting*1000,Northing*1000), proj4string=CRS("+proj=utm +zone=3"))
CPUE_coor<-spTransform(utmcoor,CRS("+proj=longlat"))
CPUE_coor

Appreciate any suggestions : )

**Comment by James-Thorson-NOAA** [comment]
so you wanna change the default plots, or the outputted densities?  If the latter, what object are you converting?

have you confirmed that the UTM zone-3 is the one being used internally?  It should show up during terminal messages when building (and also in internal objects)

**Comment by EllenY** [comment]
I'm converting the annual estimates of Northing and Eastings to plot vs year in ggplot. I'll take a look at the .cpp file

**Comment by James-Thorson** [comment]
It won't be in the CPP file ... the UTM zone is selected based on centroid
of the data by default.  It should be listed during terminal output or in
fit$extrapolation_list.

**Comment by EllenY** [comment]
Aaah. Zone 2 and not 3.
 > fit$extrapolation_list
make_extrapolation_info(.) result
      Lon              Lat           Area_km2    
 Min.   :-173.2   Min.   :59.84   Min.   : 64.0  
 1st Qu.:-171.0   1st Qu.:61.19   1st Qu.:100.0  
 Median :-169.3   Median :62.63   Median :108.0  
 Mean   :-169.1   Mean   :62.50   Mean   :108.3  
 3rd Qu.:-167.5   3rd Qu.:63.79   3rd Qu.:117.0  
 Max.   :-161.3   Max.   :65.12   Max.   :156.0  

UTM zone: 2

**Comment by EllenY** [comment]
Thank you!
