### ISSUE TITLE
Extract Center of Gravity Estimates

### ISSUE THREAD

**Issue by kkurth7** [James-Thorson-NOAA/VAST#348]
Hello, 

What is the best way to obtain/extract center of gravity coordinates by year? I have found advice including this thread https://github.com/pfmc-assessments/geostatistical_delta-GLMM/issues/12 and the function plot_range_edge, but the former seems related to the deprecated package and the latter did not seem to extract coordinates. Is there a function to accomplish this in VAST? 

Are the .rmd single and multi-species vignettes referenced in old materials archived somewhere? If possible, I would like to access them to work through examples with more guidance than the example code. Thank you!

Katherine

**Comment by kkurth7** [comment]
Thank you for your quick reply, Jim! Can you clarify the units for COG_hat? They don't align with latitude and longitude or UTM locations in the Bering Sea (I'm using the EBS pollock example data) and I can't discern the units from the source code. 

The additional information on the Jekyl website is helpful, thank you for the link. Personally, for me as a very new user of VAST, it would be helpful to have a basic example (like the EBS pollock data example code) described with model choices explained and output interpretation. For example, I was watching the Week 8 Lab lecture on the FishStats YouTube channel and heard that multispecies models are too sensitive for science issues such as climate-impact analyses. However, I haven't come across general recommendations like this in the form of a basic example and am unsure what current recommendations are and what only applies to the deprecated package.

**Comment by James-Thorson-NOAA** [comment]
Please email me about the COG units ... they're in the units for `fit$data_list$Z_gm` and should be in UTM km by default.

default choices for multivariate models are not documented anywhere, but happy to collaborate on expanding Jekyl website or a paper :)
