### ISSUE TITLE
Interpreting note on TMBhelper::sdreport

### ISSUE THREAD

**Issue by lkghart** [James-Thorson-NOAA/VAST#349]
I was wondering whether there might be documentation somewhere online or in the package listing all of the VAST warning/error messages and what they might mean? 

A red note came up while running a VAST model, and I'd like to know what it means:
"Note that 'getReportCovariance=FALSE' causes an error in 'TMB::sdreport' when no ADREPORTed variables are present"

Any guidance you can provide would be much appreciated!

-Lilian Hart
M.S. student University of Alaska Fairbanks

**Comment by eveve39** [comment]
Hi, any updates about this? I got this message. Thanks

**Comment by James-Thorson-NOAA** [comment]
you can ignore that message.  VAST itself is frozen (maintaining it for dependency updates but that's basically it) and feel free to try tinyVAST for a more user-friendly interface.
