### ISSUE TITLE
How to highlight the autocorrelation on estimated spatiotemporal variation across seasons and years when use Seasonal VAST?

### ISSUE THREAD

**Issue by Hanqingpeng** [James-Thorson-NOAA/VAST#350]
How to highlight the autocorrelation on estimated spatiotemporal variation across seasons and years when use Seasonal VAST?
The approach to fill gaps with a spatiotemporal model depends upon the temporal and spatial autocorrelated structure, which allows estimating density in non-observed locations.  Thus, it is essential to highlight the autocorrelation on estimated spatiotemporal variation across seasons and years.

**Comment by James-Thorson-NOAA** [comment]
Do you mean to ask how best to visualize and illustrate the effect of autocorrelation across Year-Seasons in the epsilon term?

I don't have any generic advice except plotting epsilon and plotting a few Year-Season panels that show it.  That's what I did in the ICESJMS paper introducing the method.  

happy to keep discussing here, but closing for now
