### ISSUE TITLE
Switch off one linear predictor

### ISSUE THREAD

**Issue by Mahdi2022** [James-Thorson-NOAA/VAST#352]
I have tried to switch off one of the linear predictors in the VAST setting but I am surprised that VAST produces estimates for both linear predictors even when one of them is switched off in the settings. Manuals imply that it should be possible to fit a VAST model with just a single linear predictor for example only occurrence or positive catch rate. How we can estimate only one linear predictor in VAST and switch off the other one? 
Another question is that is it possible to extract the variance-covariance matrix of parameters from a VAST output? In most LM, GLM and GLMM -software weget it with function vcov(), but I don’t know about VAST.

**Comment by James-Thorson-NOAA** [comment]
Yes, you can use e.g., ObsModel = c(2,4) with FieldConfig turned off for linear-predictor-1 or 2 to model just positive catch rates (i.e., eliminating the 1st component of the delta model, and fitting only to data >0).

What exactly are you trying to do?

closing for now but happy to discuss

**Comment by Mahdi2022** [comment]
Thanks! We are trying to use VAST model to find the effect of some covariates of our response variable. We only have one response variable, and some covariates affect the occurrence of response (encounter probability) and some covariates affect the incidence of response (positive catch rates). So, we want to make a VAST setting like: 
1- Turn off the first linear predictor as you said 
2- Turn off the second linear predictor 
3- Having the mix of covariates for example first linear predictors for some covariates and the second linear predictors for the rest (I don't know is it possible or not)

I tried to make the encounter probability off with FieldConfig = c("Omega1"=0, "Epsilon1"=0, "Omega2"=1, "Epsilon2"=1). and then I got both estimates for two linear predictors in results (I am using the older version of VAST). As you said, I should change the ObsModel = (2,4) to turn off the first linear predictor. How about if I want to turn off the second linear predictor? or having the mix of those as I mentioned above (number 3)?

**Comment by James-Thorson-NOAA** [comment]
Hmm.  I'm not entirely following ... it sounds like you have a delta-model, and don't want to turn off a "linear predictor", instead you just want to turn off some covariates for one predictor, and other covariates for the other.  Is that right?

If yes, the ignore what I said earlier and just using `X1_formula` and `X2_formula` to specify the desired (presumably density) covariates for each linear predictor.

And if I'm still misunderstanding, please email me directly and we can talk about how to route a request for detailed help.
