### ISSUE TITLE
Error by acoustic transect data in VAST

### ISSUE THREAD

**Issue by dongworks97** [James-Thorson-NOAA/VAST#355]
Hi everyone! I'm just starting to learn to use VAST but I met some problems in "Index standardization ". I used the biomass density data from an acoustic survey to make the calculation in g/m2. Then I met an error.
```
Check bounds for the following parameters:
     Param  starting_value    Lower      MLE    Upper  final_gradient
4 logkappa1    -0.1053605 -5.035417 -2.567023 -2.567023 -8.018384e-06

Error: Please change model structure to avoid problems with parameter estimates and then re-try; see details in `?check_fit
```
Error: Please change model structure to avoid problems with parameter estimates and then re-try; see details in `?check_fit
I modified by referring to the method provided by James in Issues and adjusted the upper limit of the parameter.
```
fit_orig = fit_model( ..., run_model=FALSE )
Lower = fit$tmb_list$Lower
# Change some bounds in Lower using grep(.) etc.
fit = fit_model( ..., lower=Lower )
```
After this, I encounter the second error.
```
In (function (obj, fn = obj$fn, gr = obj$gr, startpar = NULL, lower = -Inf, :
 Hessian is not positive definite, so standard errors are not available
```
I don't know if you've had the same problem, I hope you can help me solve this error.
I try to normalize, log10 and ln the original data. Only normalized data can complete the calculation, but the plot results are also incomprehensible.

Then, @James-Thorson-NOAA tell me try:
1. Turning off geometric anisotropy?
2. Rebinning the transects at a coarser resolution?

I tried to convert the acoustic transect data to density data by 0.5°X 0.5°station. But I'm having the same problem as before. And the problem of the "ln_H_input" not being able to change the upper and lower limits is more prominent, and I can't solve it for now.  About “1.Turning off geometric anisotropy?”, I can't find how to modify this part of the code on "make_settings" in VAST.I want you can solve my problem.

![image](https://user-images.githubusercontent.com/35809621/207896939-5da4f99d-24ad-4617-9a59-e40672b7b381.png)

**Comment by dongworks97** [comment]
But I try to turn off anisotropy, it's still not working properly.
```
make_settings(n_x=50, Region='User',
                          purpose="index2", bias.correct=FALSE,
                          knot_method='grid',
                          ObsModel=c(1,3),
                          max_cells = 500,
                          fine_scale=FALSE)
```

```
### Checking model at initial values
Error in if (any(Gradient0 == 0)) { : 
  missing value where TRUE/FALSE needed
```

**Comment by James-Thorson-NOAA** [comment]
Could you please try 

```R
fit = fit_model(..., run_model=FALSE)
Obj = fit$tmb_list$Obj
Obj$gr(Obj$par)
```

and then copy the terminal output here for me to identify what parameter is not functioning as intended?  Or send me a [minimal example](https://github.com/pfmc-assessments/geostatistical_delta-GLMM/wiki/How-to-create-a-minimal-example) to inspect locally?

**Comment by dongworks97** [comment]
Maybe it's not successful convergence. but I don't know how to modify the parameters later.
```
> Obj$gr(Obj$par)
Matching hessian patterns... Done
outer mgc:  148404 
 [1]  5.427322e+00 -2.463891e+00  3.095102e-07 -3.081490e-07 -3.931298e+02 -3.016437e+02 -7.791656e+02
 [8] -4.339731e+02 -2.416455e+02 -5.985980e+02 -4.676715e+02 -6.647968e+02 -5.281405e+02 -6.856405e+02
[15] -3.514171e+02 -4.308035e+02 -6.702144e+02 -4.825072e+02 -2.285234e+02 -5.064245e+02 -1.866685e+04
[22]  1.863943e+04  1.484040e+05
```

**Comment by James-Thorson-NOAA** [comment]
I sent some specific requests by email, but could you also do this gradient check instead as:

```R
cbind( Obj$par, Obj$gr(Obj$par) )
```

I should have asked that originally .. it then provides the parameter name and starting value for each parameter.

**Comment by James-Thorson-NOAA** [comment]
I think we got this sorted via two fixes:

- Fixing the extrapolation-grid supplied to cover all samples;
- Switching `ObsModel` and `FieldConfig` to account for 100% encounter rate resulting from acoustical data being fitted.

Happy to keep discussing here if helpful
