### ISSUE TITLE
Error about hessian

### ISSUE THREAD

**Issue by CCCRonaldooo** [James-Thorson-NOAA/VAST#357]
When I fit_model, the warning "Hessian is not positive definite, so standard errors are not available" will appear. This also seems to have led to the 'Skipping plot' in the plot function, I wonder whether there is something wrong with my data.

**Comment by James-Thorson-NOAA** [comment]
Yes, the Hessian is not positive definite indicates that there's some problem with the model and that results should not be trusted.  I recommend simplifying the model to identify, inspecting the parameter estimates to see if there's any evidence which parameter is not well identified.
