### ISSUE TITLE
(www.github.com/james-thorson/VAST/examples)is not working

### ISSUE THREAD

**Issue by ilouwei** [James-Thorson-NOAA/VAST#360]
hello， James Thorson
I am a newbie using R to learn vast package, I have learned some mathematical concepts, but I feel difficulty in the configuration of parameters, this problem occurs during the use of TMBhelper::fit_tmb (Error in nlminb(start = startpar, objective = fn, gradient = gr , control = nlminb.control), but I can't find the example file, please where can I find the latest code example, thanks a lot!
louwei

**Comment by James-Thorson-NOAA** [comment]
There's some more detailed tutorials here: https://james-thorson-noaa.github.io/docs/tutorials

**Comment by ilouwei** [comment]
> 这里有一些更详细的教程：[https ://james-thorson-noaa.github.io/docs/tutorials](https://james-thorson-noaa.github.io/docs/tutorials)

Thank you very much
