### ISSUE TITLE
Spatially varying Day of the year as catchability covariate

### ISSUE THREAD

**Issue by BioCatFish** [James-Thorson-NOAA/VAST#369]
Hi guys!

I'm working on a project to compare juvenile salmon from western and eastern Bering Sea. 
I'm modelling biomass and density averaged body condition (according to the example: https://github.com/James-Thorson-NOAA/VAST/wiki/Correlations-between-fish-condition-and-density).

I use SST as a spatially and temporally invariant habitat covariate and Julian day of the year (DOY) as a catchability covariate.
When modelling body condition using DOY as a spatially invariant covariate seems reasonable since the fish growth is assumed to not vary spatially.

However I'm a bit concerned about using DOY as a spatially invariant covariate to model biomass because juvenile salmon are actively migrating fish and DOY effect at one location (say near the shore) should be different at another location (far offhore). 

I understand the concept of using spatially-varying effect of regional indices (Thorson, 2019, https://doi.org/10.1002/lno.11238) but I am struggling to understand if it's possible and makes any sense to use DOY (which is different at each station) as spatially-varying catchability covariate.

I appreciate any advice on that!

Thank you,

Aleksei Somov.

**Comment by James-Thorson-NOAA** [comment]
I think it's a great idea!  We explored in detail using a discrete-valued season indicator with a spatially varying coefficient to estimate a seasonal movement ([here](https://www.sciencedirect.com/science/article/pii/S0079661123000782?casa_token=86rngJPK0q8AAAAA:z_x1MDq_Yc0Rc7_TIEPqCPorM1cPClJbVFnP_PKw_mDSit05xo6rGeGbguyjk3TVemcaUUEGE1s)).  Similarly, my draft textbook has an example involving a cyclic spline for calendar date and spatially varying coefficient to model intra-annual dynamics.  Presumably an SVC for date would then represent movement occurring during the surveyed season ...?

closing here but happy to keep discussing :)
