### ISSUE TITLE
Poisson-link model application

### ISSUE THREAD

**Issue by BioCatFish** [James-Thorson-NOAA/VAST#370]
Hi! I would like to get some clarification on data preparation for a model which estimates biomass.
If I use a conventional delta-model which considers encounter probability and positive catch rates the model settings should be:
ObsModel=c(2,0),
"b_i"=as_units(catch_kg, "kg"),
"a_i"=as_units(temp[,'area_swept_km2'],"km^2").

If apply [poisson-link model](https://cdnsciencepub.com/doi/full/10.1139/cjfas-2017-0266?casa_token=Tk9CgHtb0PQAAAAA%3AAVMlr97mc0YZxNDJTpjUYt61BdKEUzwueWHtnVrtw2UN2iabZWFSw_T37NYwz8-H-yIXGGREByfI) is said that "Poisson-link model is derived by defining n_i as the predicted density of individuals or groups at sample i, where the number of observed individuals is assumed to follow a Poisson process with expectation n_i".

In this case should I input in the "b_i" both catches in kg and numbers of individuals caught?

Thanks.

**Comment by James-Thorson-NOAA** [comment]
It's mainly a way of expressing that the mean-variance relationship is derived from a Poisson process.  I wouldn't overinterpret the linear predictors themselves.

**Comment by BioCatFish** [comment]
Thanks James. 
So, using the Poisson-link model can interpret combined resulted covariate effects on 1st and 2nd linear predictors on  final density just as their sum since the response is then exp(LP-1) * exp(LP-2)?

**Comment by James-Thorson-NOAA** [comment]
Yes, except it's the additive effect on *log* density , i.e., log(D) = LP-1 + LP-2 (re-iterating what you have above)
