### ISSUE TITLE
Creating extrapolation grid: shifted south

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#372]
Any thoughts on why this might be happening?
In creating an extrapolation grid from my eastern Bering Sea data.
![image](https://github.com/James-Thorson-NOAA/VAST/assets/7538663/28c6ec48-5ac1-4919-8cca-ecdde923ab25)
The extrapolation grid is about 4 degrees south of the actual station data.
![image](https://github.com/James-Thorson-NOAA/VAST/assets/7538663/04b29f88-b7e3-484e-b781-09da0677b4b9)

Here is my code.

##############
# Create extrapolation grid with user data
##############
#https://github.com/James-Thorson-NOAA/VAST/wiki/Creating-an-extrapolation-grid
sessionInfo()
packageVersion("sf")
library(sf) #0.9.6
library(rgdal)
library(here)
library(splines)
library(sp)  # vector data
library(raster)  # raster data
library(rgdal)  # input/output, projections
library(rgeos)  # geometry ops
library(spdep)  # spatial dependence

### existing shape file.

dat<-temp_ebs #Eastern Bering Sea aata 

par(mfrow=c(1,1))
### Use this to draw points around your data
plot(dat$Lon, dat$Lat)
LL <- locator()
saveRDS(LL, 'CC_extent_LL.rds')

## define the outer limits of the region (the extent).
LL <- readRDS('CC_extent_LL.rds')
region_extent <- data.frame(long=LL$x, lat=LL$y)
str(region_extent)
## Need to duplicate a point so that it is connected
region_extent <- rbind(region_extent, region_extent[1,])
## https://www.maths.lancs.ac.uk/~rowlings/Teaching/Sheffield2013/cheatsheet.html
poly <- Polygon(region_extent)
polys <- Polygons(list(poly), ID='all')
sps <- SpatialPolygons(list(polys))
## I think the F_AREA could be dropped here
sps <- SpatialPolygonsDataFrame(sps, data.frame(Id=factor('all'), F_AREA=1, row.names='all'))
proj4string(sps)<- CRS("+proj=longlat +datum=WGS84")
sps <- spTransform(sps, CRS("+proj=longlat +lat_0=90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 "))

## longitude
lon <- sum(bbox(sps)[1,])/2
## for new CRS
utmzone <- floor((lon + 180)/6)+1
crs_LL <- CRS('+proj=longlat +ellps=WGS84 +no_defs')
sps@proj4string <- crs_LL
### Method 2: Get it from an existing shapefile.
#library(rgdal) # '1.5.18'
#shp <- readOGR("ebs.shp", layer="ebs")
#sps <- spTransform(shp, CRS("+proj=longlat +lat_0=90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 "))
#lon <- sum(bbox(sps)[1,])/2
## for new CRS
#utmzone <- floor((lon + 180)/6)+1
## Convert the final in polygon to UTM
crs_UTM <- CRS(paste0("+proj=utm +zone=",utmzone," +ellps=WGS84 +datum=WGS84 +units=m +no_defs "))
region_polygon <- spTransform(sps, crs_UTM)

## the resolution of the grid.
cell_size <- 2000
## This step is slow at high resolutions
region_grid <- st_make_grid(region_polygon, cellsize = cell_size, what = "centers")
## Convert region_grid to Spatial Points to SpatialPointsDataFrame
region_grid <- as(region_grid, "Spatial")
region_grid_sp <- as(region_grid, "SpatialPointsDataFrame")
## Id) in your data frame))
region_grid_sp@data <- over(region_grid, region_polygon)

## Convert back to lon/lat coordinates as that is what VAST uses
region_grid_LL <- as.data.frame(spTransform(region_grid_sp, crs_LL))
region_df <- with(region_grid_LL,
                  data.frame(Lon=coords.x1,
                             Lat=coords.x2, Id,
                             Area_km2=( (cell_size/1000)^2),
                             row=1:nrow(region_grid_LL)))
## Filter out the grid that does not overlap (outside extent)
region <- subset(region_df, !is.na(Id))
## This is the final file needed.
str(region)
### Save it to be read in and passed to VAST later.
saveRDS(region, file = "user_region_arctic.rds")
saveRDS(region, file = "user_region_ebs.rds")

### Quick plots of the process for method 1
png('user_region_ebs.png', width=7, height=7, units='in', res=200)
par(mfrow=c(2,2))
with(region_extent, plot(long, lat, main='Extent in points in LL'))
plot(region_polygon, main='Polygon in UTM', axes=TRUE)
plot(region_grid, col=ifelse(is.na(region_df$Id), 'red', 'black'),
     axes=TRUE, main='Extrapolation area UTM')
with(region, plot(Lon, Lat, main='Extrapolation region in LL', pch='.'))
dev.off()

**Comment by James-Thorson-NOAA** [comment]
Sorry to hear that you're having difficulties constructing the extrapolation grid.  I don't maintain that community-contributed page that outlines one way to do so ... the `?make_extrapolation_info` notes other ways including constructing a data frame and providing a shapefile.  

Personally, I would recommend running the steps line by line and frequently inspecting and/or plotting the object last created to see where it goes awry and then exploring that piece to identify the problem.  Offhand, I'm guessing it's some problem with the projection being called.  

I'm closing for now (as it is a problem outside of VAST) but happy to keep discussing here.  Or feel free to request an invite to the Slack channel from the github README

**Comment by EllenY** [comment]
Coordinates are read in incorrectly if zoom settings in global options are different from 100%. Try this:

Tools -> Global Options... -> Appearance -> Zoom: 100%

https://stackoverflow.com/questions/73256552/problem-with-point-location-with-locator-function-in-r

**Comment by EllenY** [comment]
Thanks Jim!  I stepped thru the lines. My issue was with locator() and a setting in Global Options. Here’s a fix. https://stackoverflow.com/questions/73256552/problem-with-point-location-with-locator-function-in-rOn Jun 29, 2023, at 3:00 PM, Jim Thorson ***@***.***> wrote:﻿
Sorry to hear that you're having difficulties constructing the extrapolation grid.  I don't maintain that community-contributed page that outlines one way to do so ... the ?make_extrapolation_info notes other ways including constructing a data frame and providing a shapefile.
Personally, I would recommend running the steps line by line and frequently inspecting and/or plotting the object last created to see where it goes awry and then exploring that piece to identify the problem.  Offhand, I'm guessing it's some problem with the projection being called.
I'm closing for now (as it is a problem outside of VAST) but happy to keep discussing here.  Or feel free to request an invite to the Slack channel from the github README

**Comment by James-Thorson-NOAA** [comment]
Wow, that's an unexpected issue!  Thanks for diagnosing the problem and finding an explanation.  I have updated the community-contributed demo [here](https://github.com/James-Thorson-NOAA/VAST/wiki/Creating-an-extrapolation-grid).
