### ISSUE TITLE
Error running seasonal model example

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [James-Thorson-NOAA/VAST#377]
I get an error running the seasonal model example from the Wiki

[https://github.com/James-Thorson-NOAA/VAST/wiki/Seasonal-model](https://github.com/James-Thorson-NOAA/VAST/wiki/Seasonal-model)

I get this error:

> ### Making spatial information
> Error in loc_orig[, 1] : incorrect number of dimensions

when running the code that starts on line 88.

```
#####
## Model fit -- make sure to use new functions
#####

fit_orig = fit_model("settings" = settings,
                     "Lat_i" = samp_dat[, 'Lat'],
                     "Lon_i" = samp_dat[, 'Lon'],
                     "t_i" = samp_dat[, 'year_season'],
                     "b_i" = samp_dat[, 'weight'],
                     "a_i" = samp_dat[, 'Swept'],
                     "X1config_cp" = X1config_cp_use,
                     "X2config_cp" = X2config_cp_use,
                     "covariate_data" = cov_dat,
                     "X1_formula" = formula_use,
                     "X2_formula" = formula_use,
                     "X_contrasts" = list(Season = contrasts(cov_dat$Season, contrasts = FALSE), Year_Cov = contrasts(cov_dat$Year_Cov, contrasts = FALSE)),
                     "run_model" = FALSE,
                     "PredTF_i" = samp_dat[, 'Dummy'] )
```

Session Info:

> R version 4.2.2 (2022-10-31 ucrt)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19045)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.utf8    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] VAST_3.10.1            FishStatsUtils_2.12.1  marginaleffects_0.15.0 units_0.8-4            TMB_1.9.6             
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.11        INLA_23.04.24      pillar_1.9.0       compiler_4.2.2     class_7.3-22       tools_4.2.2        lubridate_1.9.2    lifecycle_1.0.3    tibble_3.2.1      
> [10] lattice_0.21-8     timechange_0.2.0   pkgconfig_2.0.3    rlang_1.1.1        Matrix_1.6-1       DBI_1.1.3          cli_3.6.1          rstudioapi_0.15.0  coldpool_3.1-1    
> [19] e1071_1.7-13       terra_1.7-46       dplyr_1.1.3        raster_3.6-23      generics_0.1.3     vctrs_0.6.3        classInt_0.4-10    rprojroot_2.0.3    grid_4.2.2        
> [28] tidyselect_1.2.0   glue_1.6.2         data.table_1.14.8  here_1.0.1         sf_1.0-14          R6_2.5.1           fansi_1.0.4        RANN_2.6.1         sp_2.0-0          
> [37] magrittr_2.0.3     splines_4.2.2      codetools_0.2-19   utf8_1.2.3         KernSmooth_2.23-22 proxy_0.4-27

**Comment by aallyn** [comment]
Hi Sean, 

I think this might be happening because it is using some pre-existing extrapolation knot/grid files. If you check out your working directory and look for .RData files named "Kmeans_knots" and "Kmeans_extrapolation," you can move these (or delete them if they aren't needed anymore) and then re-run the example and I think it should work? The other signal that this could be the problem is that when running the example code there was a message printed to console after the "### Making extrapolation-grid" that mentioned loading some existing Kmeans_extrapolation file. Hope that helps!

**Comment by sean-rohan-NOAA** [comment]
Ah, yep that solved it. Thank you!
