### ISSUE TITLE
How do you define strata.limits?

### ISSUE THREAD

**Issue by smormede** [James-Thorson-NOAA/VAST#384]
Hello,

I am looking for examples of definition of strata limits, to get outputs of biomass indices in different areas, with CVs. I have been pouring over the help files and git and not found how to define strata limits apart from the example in a closed issue, which had depth and north/south. The make_settings help refers to example scripts which I can't find. 

I'm after a simple spatial split, in a kind of a t-shape in space (latitude -46 and longitude 176 below that), although it would be helpful to be able to make that more complex. 

Thanks for your help.

Sophie

**Comment by James-Thorson-NOAA** [comment]
Sorry for the slow response!  

My memory is that the easiest way to do this is to manually override `extrapolation_list$a_gl` using psuedocode below:

```R
fit0 = fit_model( ..., run_model=FALSE)
extrap = fit0$extrapolation_info
extrap$a_gl = [INCLUDING MULTIPLE COLUMNS AND SAME NUMBER OF ROWS]
fit = fit_model( ..., extrapolation_list = extrap)
```

Alternatively, you could try out tinyVAST (in alpha release), which uses the standard regression interface and hence requires `newdata` for each stratum.

**Comment by smormede** [comment]
thanks Jim, I'll try that. I have looked at tinyVAST briefly but not seen examples /wiki etc as has been developed over time for VAST. So I've been a little bit reluctant to switch over just yet. I will eventually though.

**Comment by James-Thorson-NOAA** [comment]
Yeah, we're hoping to build out a bookdown site for tinyVAST ... for now it's just the vignettes [here](https://vast-lib.github.io/tinyVAST/articles/)

**Comment by smormede** [comment]
Hi Jim,

I seem to be having issues with the syntax somewhere. I followed the instructions above, but I'm still getting a single index.

Maybe the issue is in the syntax of a_gl. I have tried:
* one column with a different number for each stratum (or different stratum name)
* one column per stratum with a 1 for being that stratum and 0 otherwise
* one column per stratum with a unique number for each stratum and 0 otherwise

when I run plot(fit,plot_set=3) I get a single index called Stratum_1. And fit$strata_names is null for all of these options. I gather fit$strata_names is what the plotting function uses to decide on strata?

Or could it be an incompatibility with settings, which is created using make.settings() and therefore has a strata.limits of "All_strata"

Any suggestions?

Thanks

Sophie

**Comment by James-Thorson-NOAA** [comment]
Could you send a minimal example using suggested format
<https://github.com/pfmc-assessments/geostatistical_delta-GLMM/wiki/How-to-create-a-minimal-example>,
presumable loading inputs, running fit_model( run_model=FALSE), modifying
extrapolation_list, and then running fit_model( extapolation_list=extrap) ?

Alternatively, I'm guessing you'll need to just look through the contents
of constituent functions.

**Comment by James-Thorson** [comment]
Sorry for the slow response.  It requires editing `extrapolation_list$a_el` and see example below.  I'm closing, but feel free to keep iterating as needed.

```R
# Load package
library(VAST)

# load data set
# see `?load_example` for list of stocks with example data
# that are installed automatically with `FishStatsUtils`.
example = load_example( data_set="EBS_pollock" )

# Make settings (turning off bias.correct to save time for example)
settings = make_settings( n_x = 100,
  Region = example$Region,
  purpose = "index2",
  bias.correct = FALSE )

# Run model
fit = fit_model( settings = settings,
  Lat_i = example$sampling_data[,'Lat'],
  Lon_i = example$sampling_data[,'Lon'],
  t_i = example$sampling_data[,'Year'],
  b_i = example$sampling_data[,'Catch_KG'],
  a_i = example$sampling_data[,'AreaSwept_km2'],
  run_model = FALSE )

# Duplicating single stratum twice as example
extrap = fit$extrapolation_list
extrap$a_el = cbind( "Stratum_1"=extrap$a_el, "Stratum_2"=extrap$a_el)

#
fit = fit_model( settings = settings,
  Lat_i = example$sampling_data[,'Lat'],
  Lon_i = example$sampling_data[,'Lon'],
  t_i = example$sampling_data[,'Year'],
  b_i = example$sampling_data[,'Catch_KG'],
  a_i = example$sampling_data[,'AreaSwept_km2'],
  extrapolation_list = extrap,
  run_model = TRUE )

# Plot results
plot( fit )
```

**Comment by smormede** [comment]
That worked, thanks Jim.
