### ISSUE TITLE
Visualizing data gaps and autocorrelation

### ISSUE THREAD

**Issue by abesolberg** [James-Thorson-NOAA/VAST#387]
Hi Jim,

I apologize if this is not the right forum for this question. I have a seasonal model which has many sampling gaps: it is a model of 25 years each with 17 bi-weekly interval seasons. In the season-year combinations where gaps are being filled by the model, I'd like to have a better sense/way of visualizing where specifically the model is pulling from. 

Is there a way to modify the `plot_anisotropy` code to show distance for 95% correlation, 90% correlation, etc. to make some kind of contour map to show where the data is coming from spatially? In addition to the autocorrelation plots in your ICEJMS (2020) paper, is there a way to better visualize spatial-temporal autocorrelation that could provide more insight on the primary driver of my final model output in situations where areas weren't sampled?  

Quick addendum: Am I correct in understanding that the seasonal and annual main effects on the first two linear predictors are `gamma1_cp` & `gamma2_cp`? What do the other fixed effects, `log_sigmaXi1_cp`  and`log_sigmaXi2_cp`, represent (each have the same dimensions as n_year + n_season)? I do not have a spatial main effect, as I set `Omega1 = 0` and `Omega2 = 0`.

Thanks in advance!

**Comment by James-Thorson** [comment]
I started working on a FishStatsUtils::plot_residual_semivariance, which
uses `spacetime::STFDF` to plot the spatio-temporal semi-variance of
residuals as model check.  Perhaps that's relevant.  I'm sorry that I don't
have more advice, but it's somewhat beyond my intended scope of support.
I'm closing for now, but happy to see if others chime in.
