### ISSUE TITLE
Multimodal red snapper example fails

### ISSUE THREAD

**Issue by seanhardison1** [James-Thorson-NOAA/VAST#390]
I get the following error when running the multimodal red snapper example:

````
Check bounds for the following parameters:
       Param starting_value     Lower       MLE     Upper final_gradient
28 logkappa2     -0.1053605 -6.400635 -3.067245 -3.067245      -5.635831

Error: Please change model structure to avoid problems with parameter estimates and then re-try; see details in `?check_fit`
````

Any thoughts on how to proceed? Thanks!

**Comment by James-Thorson-NOAA** [comment]
you could do `fit_model( ..., test_fit = FALSE)`.  Or honestly, I recommend doing the [same model in tinyVAST](https://vast-lib.github.io/tinyVAST/articles/multiple_data.html), which has a simpler interface IMO.

**Comment by seanhardison1** [comment]
yep, that works, thanks Jim! Got it working in tinyVAST too.
