### ISSUE TITLE
Compilation failed while running fit_model() using R 4.0.2

### ISSUE THREAD

**Issue by johannafaure** [James-Thorson-NOAA/VAST#391]
Hello ! 

I am trying to run fit_model() using R version 4.0.2 so I can run within Microsoft R Open 4.0.

I installed VAST as follow : devtools::install_github("James-Thorson-NOAA/VAST", ref="main") 
and I set VAST_v14_0_1 in settings. 

When running the following code, I obtain a compilation error with TMB object : 

 fit <- fit_model( settings = settings, Lat_i = Lat_i, Lon_i = Lon_i, 
	t_i = as.numeric( as.character( spp_data[, "Year"] ) ), c_i = rep( 0, nrow( spp_data ) ), 
	b_i = as.numeric( as.character( spp_data[, "CPUE_mean"] ) ), a_i = rep( 1, nrow( spp_data ) ), 
	v_i = v_i - 1, Use_REML = FALSE, input_grid = input_grid, 
	newtonsteps = 3 )

### Making TMB object
Error in TMB::compile(file = paste0(Version_framework, ".cpp"), framework = framework,  : 
  Compilation failed

I tried to uninstall VAST and TMB packages, re-install Rtools 4.0 and then VAST, but I still get the same error when running fit-model(). 

Could you please tell me how to solve this issue? I have TMB version 1.9.12

Thanks a lot

**Comment by agruss2** [comment]
Hi Johanna, 

Regarding your compiling error –
Could you please try something else? 
(1) Uninstall VAST and TMB packages and then re-install Rtools 4.0 
(2) Make sure that Rtools 4.0 is in your PATH by doing the following:
(i) Type “env” in the search box.
(ii) Select “Edit the system environment variables”.
(iii) Click on “Environment variables…”
(iv) In “use variables” double-click on “Path”.
(v) If rtools40 does not appear in your Path add it.
(3) Only after that re-install VAST. 

Hopefully that solves you issue. Sorry that I did not think about this earlier.

@James-Thorson-NOAA and VAST users - Please let us know if you have other ideas in case mine is not going to solve the problem that Johanna is facing.

Cheers, 
Arnaud

**Comment by agruss2** [comment]
Issue solved :)
