### ISSUE TITLE
Fix for extrapolation area plot

### ISSUE THREAD

**Issue by perretti** [James-Thorson-NOAA/VAST#74]
For the NE Shelf, I noticed that the extrapolation plot produced by Plot_data_and_knots was not matching the strata I put in (it always just plots all strata). I fixed it by changing all instances of "which(Extrapolation_List$Area_km2_x > 0)" to "which(Extrapolation_List$a_el > 0)".

**Comment by James-Thorson-NOAA** [comment]
I think this is now fixed.
